### PR TITLE
Buttons & lights & relays providers refactoring

### LINKED ISSUE #2222: TUYA Dimmer behaves erratically (1.14.1, 1.14.2-dev)
**Bug description**
1. When switching ON, channel #0 gets reset to 1. Visual effect: The connected light appears to be switched on with the last brightness, then turns off (flashes briefly). This behaviour is the same using either the Web UI switch or the physical switch on the device.

2. Cannot be switched to "ON" if brightness isn't set to "255" before. Lower levels lead to an immediate automatic switch OFF.

3. Brightness control
a) switches the light OFF when set to zero (seems ok to me).
b) sometimes also moves the Channel #0 slider, sometimes doesn't.

4. Channel #0 seems to be the only way to set the light’s brighness but appears to "jump", apparently adding 16 to the value. Also, the brightness slider has to be 255 initally for this to work.

**Steps to reproduce**
See above.

**Expected behavior**
1. Should switch on to the last brightness set.
2. Should be able to switch regardless of slider settings.
3a. OK
3b. For a one-channel light, brightness should be the same as channel #0. 
4. Channel #0 should keep the set value.

**Screenshots**
None

**Device information**
[975817] [MAIN] ESPURNA 1.14.2-dev (2dcf1b2b)
[975817] [MAIN] xose.perez@gmail.com
[975817] [MAIN] http://tinkerman.cat

[975817] [MAIN] CPU chip ID: 0xF9244C
[975817] [MAIN] CPU frequency: 80 MHz
[975817] [MAIN] SDK version: 1.5.3(aec24ac9)
[975817] [MAIN] Core version: 2.3.0
[975820] [MAIN] Core revision: 9826c6d
[975820] [MAIN] Build time: 1586397641
[975820] 
[975821] [MAIN] Flash chip ID: 0x1540C8
[975821] [MAIN] Flash speed: 40000000 Hz
[975821] [MAIN] Flash mode: DOUT
[975821] 
[975822] [MAIN] Flash size (CHIP)   :  2097152 bytes /  512 sectors (   0 to  511)
[975827] [MAIN] Flash size (SDK)    :  1048576 bytes /  256 sectors (   0 to  255)
[975827] [MAIN] Reserved            :     4096 bytes /    1 sectors (   0 to    0)
[975827] [MAIN] Firmware size       :   527520 bytes /  129 sectors (   1 to  129)
[975828] [MAIN] Max OTA size        :   495616 bytes /  121 sectors ( 130 to  250)
[975828] [MAIN] EEPROM size         :     4096 bytes /    1 sectors ( 251 to  251)
[975828] [MAIN] Reserved            :    16384 bytes /    4 sectors ( 252 to  255)
[975828] 
[975829] [MAIN] EEPROM sectors: 251, 250
[975833] [MAIN] EEPROM current: 250
[975833] 
[975833] [MAIN] EEPROM:  4096 bytes initially |   425 bytes used (10%) |  3671 bytes free (89%)
[975834] [MAIN] Heap  : 30488 bytes initially | 17832 bytes used (58%) | 12656 bytes free (41%)
[975834] [MAIN] Stack :  4096 bytes initially |  1424 bytes used (34%) |  2672 bytes free (65%)
[975834] 
[975834] [MAIN] Boot version: 7
[975834] [MAIN] Boot mode: 1
[975838] [MAIN] Last reset reason: External System
[975838] [MAIN] Last reset info: Fatal exception:0 flag:6 (EXT_SYS_RST) epc1:0x00000000 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
[975838] 
[975839] [MAIN] Board: TUYA_GENERIC_DIMMER
[975839] [MAIN] Support: ALEXA API BROKER BUTTON DEBUG_TELNET DEBUG_WEB DOMOTICZ HOMEASSISTANT LED MDNS_SERVER MQTT NTP SCHEDULER TELNET TERMINAL THINGSPEAK WEB 
[975839] [MAIN] OTA: ARDUINO ASYNCTCP WEB 
[975839] [MAIN] WebUI image: LIGHT
[975840] 
[976081] [MAIN] Firmware MD5: c71b3e21481540a09d4cdcb9f99a44ea
[976086] [MAIN] Power: 3252 mV
[976086] [MAIN] Power saving delay value: 10 ms
[976086] 

**Tools used**
* *Desktop operating system*
Linux Mint 19.3; Ubuntu 14.04.5
* *Browser & version*
Firefox 66.0.3
* *IDE & version*
No IDE, esptool.py to initially flash espurna-1.14.1-tuya-generic-dimmer.bin.
Web UI OTA to flash a) espurna-1.14.2-dev.nightly20200409+git2dcf1b2b-espurna-core-webui-1MB.bin then b) espurna-1.14.2-dev.nightly20200409+git2dcf1b2b-tuya-generic-dimmer.bin.

* *Compiler & version (if not embedded in IDE)*
None used.

**Additional context**
Please let me know if and how I might help.
I have two of these devices and should very much appreciate if we could make them work. All my other devices also use Espurna and I really wouldn't like to be forced to move to another platform.

Since all the basic functionality is there, I think these might only be some small bugs, maybe in the communication with the MCU?

### PR DESCRIPTION
**Pull request by mcspr**
- gpio module now tracks the known providers (right now, hardware and mcp expander)
- refactored relay struct to use 'Provider' implementing setup,notify,change,boot instead of just BasePin actions
- refactored button module to use gpio provider instead of referencing types itself
- removed dual & stm code from buttons, migrate both to relay module
- added status notify and change callbacks for relayStatus (i.e. 'notify' when relay status was called, but not changed. and 'changed' when it did)  
- relays runtime configuration keys
- relay command now shows configured relays and current & target statuses
- refactor the code using relayStatus(0, blah) under LIGHT_PROVIDER check to use lightState instead
- remove rfbridge code form relay module. implement through a basic state listener in the rfbridge module, depend on RELAY_SUPPORT
- allow to bind rf codes to real relays
- drop tuya-specific lights provider, remove tuya code from relays and lights modules
- integrate tuya via relay listeners and providers, use lights custom provider
- implement channel transitions for tuya. disabled by default, and transition time and step are overridden to 2000 + 100. needs to be set to some value below the total time (i.e. `total transition time / step time == number of steps`, we need to figure out a correct time that serial comms could handle)
- lights custom provider (global, not per-pin) and state listeners
- remove lights code from relay module. implement through providers & listeners in the lights module, depend on RELAY_SUPPORT
- lights per-channel relay provider (unused atm), depend on RELAY_SUPPORT
- refactored channel transition - calculate step only once, make sure time + step values are sane, generate quick transitions with very small delay (10ms hardcoded) for transitions during OFF state i.e. we no longer waste 500ms (or whatever transition time is set to) on boot doing nothing
- transition time + step parameter for the lightUpdate
- report mask parameter for the lightUpdate
- minor fixes across the board

resolve #2222

### CODE REVIEW

**Comment by mcspr** [comment]
Notice that `LIGHT_PROVIDER_TUYA` is removed, proper lights config is:
```cpp
#define TUYA_SUPPORT 1
#define LIGHT_PROVIDER LIGHT_PROVIDER_CUSTOM
```
I missed that earlier commits did not actually set the tuya_support flag

**Comment by davebuk** [comment]
- Built using the definitions set in platformio.ini 1.15.0-dev (3fea207f). After initial first boot, two switches are shown, `Switch #0 (light_global)` and `Switch #1 (tuya)`.

- Switching them ON/OFF individually gives:

```
[197222] [WEBSOCKET] Requested action: relay
[197223] [RELAY] #0 scheduled ON in 0 ms
[197230] [RELAY] #0 set to ON
[197232] [MQTT] Sending TUYA001/relay/0 => 1 (PID 55)
[197241] [MQTT] Publish ACK for PID 55
[197332] [MQTT] Sending TUYA001/channel/0 => 164 (PID 56)
[197333] [MQTT] Sending TUYA001/brightness => 255 (PID 57)
[197341] [MQTT] Publish ACK for PID 56
[197344] [MQTT] Publish ACK for PID 57
[197742] [TUYA] =>: 55aa0006000800020004000000a4b7
[198235] [RELAY] Relay mask: 0b1
[198660] [WEBSOCKET] Requested action: relay
[198661] [RELAY] #0 scheduled OFF in 0 ms
[198665] [RELAY] #0 set to OFF
[198667] [MQTT] Sending TUYA001/relay/0 => 0 (PID 58)
[198673] [MQTT] Publish ACK for PID 58
[198768] [MQTT] Sending TUYA001/channel/0 => 0 (PID 59)
[198768] [MQTT] Sending TUYA001/brightness => 255 (PID 60)
[198774] [MQTT] Publish ACK for PID 59
[198778] [MQTT] Publish ACK for PID 60
[199670] [RELAY] Relay mask: 0b0
[200112] [WEBSOCKET] Requested action: relay
[200113] [RELAY] #1 scheduled ON in 0 ms
[200118] [RELAY] #1 set to ON
[200120] [MQTT] Sending TUYA001/relay/1 => 1 (PID 61)
[200125] [MQTT] Publish ACK for PID 61
[200127] [TUYA] =>: 55aa0006000501010001010e
[200163] [TUYA] <=: 55aa0007000501010001010f
[200164] [Tuya] Received integer dp=1 value=1[200176] [TUYA] <=: 55aa0007000501010001010f
[200176] [Tuya] Received integer dp=1 value=1[200189] [TUYA] <=: 55aa00070008020200040000001026
[200193] [Tuya] Received boolean dp=2 value=#t[200194] [TUYA] <=: 55aa0007000501010001010f
[200194] [Tuya] Received integer dp=1 value=1[200219] [TUYA] <=: 55aa0007000802020004000000ff15
[200219] [Tuya] Received boolean dp=2 value=#t[201123] [RELAY] Relay mask: 0b10
[201642] [TUYA] =>: 55aa00000000ff
[201660] [WEBSOCKET] Requested action: relay
[201660] [RELAY] #1 scheduled OFF in 0 ms
[201666] [RELAY] #1 set to OFF
[201671] [MQTT] Sending TUYA001/relay/1 => 0 (PID 62)
[201676] [MQTT] Publish ACK for PID 62
[201678] [TUYA] <=: 55aa000000010101
[201678] [TUYA] =>: 55aa0006000501010001000d
[201714] [TUYA] <=: 55aa0007000501010001000e
[201715] [Tuya] Received integer dp=1 value=0[201727] [TUYA] <=: 55aa0007000501010001000e
[201727] [Tuya] Received integer dp=1 value=0[201741] [TUYA] <=: 55aa0007000802020004000000ff15
[201741] [Tuya] Received boolean dp=2 value=#t[201755] [TUYA] <=: 55aa0007000501010001000e
[201756] [Tuya] Received integer dp=1 value=0[201770] [TUYA] <=: 55aa00070008020200040000001026
[201770] [Tuya] Received boolean dp=2 value=#t[202674] [RELAY] Relay mask: 0b0
[205058] [WEBSOCKET] Requested action: channel
[205161] [MQTT] Sending TUYA001/channel/0 => 0 (PID 63)
[205161] [MQTT] Sending TUYA001/brightness => 255 (PID 64)
[205166] [MQTT] Publish ACK for PID 63
[205172] [MQTT] Publish ACK for PID 64
[207185] [WEBSOCKET] Requested action: channel
[207288] [MQTT] Sending TUYA001/channel/0 => 0 (PID 65)
[207289] [MQTT] Sending TUYA001/brightness => 255 (PID 66)
[207300] [MQTT] Publish ACK for PID 65
[207326] [MQTT] Publish ACK for PID 66
[210647] [TUYA] =>: 55aa00000000ff
[210672] [TUYA] <=: 55aa000000010101
[219653] [TUYA] =>: 55aa00000000ff
[219677] [TUYA] <=: 55aa000000010101
```
The light is not controlled by switch `#0` but is turned ON/OFF by `#1`. Dimming doesn't work and light is on 100%.

- After a power cycle, a third switch is added `Switch #2 (tuya)` and switching all three ON/OFF is turn gives:

```
[264645] [WEBSOCKET] Requested action: relay
[264646] [RELAY] #0 scheduled ON in 0 ms
[264654] [RELAY] #0 set to ON
[264656] [MQTT] Sending TUYA001/relay/0 => 1 (PID 117)
[264661] [MQTT] Publish ACK for PID 117
[264717] [TUYA] =>: 55aa00000000ff
[264743] [TUYA] <=: 55aa000000010101
[264757] [MQTT] Sending TUYA001/channel/0 => 102 (PID 118)
[264757] [MQTT] Sending TUYA001/brightness => 255 (PID 119)
[264761] [MQTT] Publish ACK for PID 118
[264765] [MQTT] Publish ACK for PID 119
[265165] [TUYA] =>: 55aa00060008000200040000006679
[265659] [RELAY] Relay mask: 0b1
[266062] [WEBSOCKET] Requested action: relay
[266063] [RELAY] #0 scheduled OFF in 0 ms
[266067] [RELAY] #0 set to OFF
[266069] [MQTT] Sending TUYA001/relay/0 => 0 (PID 120)
[266076] [MQTT] Publish ACK for PID 120
[266170] [MQTT] Sending TUYA001/channel/0 => 0 (PID 121)
[266170] [MQTT] Sending TUYA001/brightness => 255 (PID 122)
[266188] [MQTT] Publish ACK for PID 121
[266192] [MQTT] Publish ACK for PID 122
[267072] [RELAY] Relay mask: 0b0
[267684] [WEBSOCKET] Requested action: relay
[267685] [RELAY] #1 scheduled ON in 0 ms
[267692] [RELAY] #1 set to ON
[267694] [MQTT] Sending TUYA001/relay/1 => 1 (PID 123)
[267699] [MQTT] Publish ACK for PID 123
[267701] [TUYA] =>: 55aa0006000501010001010e
[267737] [TUYA] <=: 55aa0007000501010001010f
[267737] [Tuya] Received integer dp=1 value=1[267750] [TUYA] <=: 55aa0007000501010001010f
[267750] [Tuya] Received integer dp=1 value=1[267765] [TUYA] <=: 55aa00070008020200040000001026
[267765] [Tuya] Received boolean dp=2 value=#t[267781] [TUYA] <=: 55aa0007000501010001010f
[267782] [Tuya] Received integer dp=1 value=1[267795] [TUYA] <=: 55aa0007000802020004000000ff15
[267795] [Tuya] Received boolean dp=2 value=#t[268697] [RELAY] Relay mask: 0b10
[269412] [WEBSOCKET] Requested action: relay
[269413] [RELAY] #1 scheduled OFF in 0 ms
[269416] [RELAY] #1 set to OFF
[269418] [MQTT] Sending TUYA001/relay/1 => 0 (PID 124)
[269423] [MQTT] Publish ACK for PID 124
[269425] [TUYA] =>: 55aa0006000501010001000d
[269452] [TUYA] <=: 55aa0007000501010001000e
[269453] [Tuya] Received integer dp=1 value=0[269465] [TUYA] <=: 55aa0007000501010001000e
[269465] [Tuya] Received integer dp=1 value=0[269489] [TUYA] <=: 55aa0007000802020004000000ff15
[269489] [Tuya] Received boolean dp=2 value=#t[269502] [TUYA] <=: 55aa0007000501010001000e
[269505] [Tuya] Received integer dp=1 value=0[269519] [TUYA] <=: 55aa00070008020200040000001026
[269522] [Tuya] Received boolean dp=2 value=#t[270422] [RELAY] Relay mask: 0b0
[271546] [WEBSOCKET] Requested action: relay
[271547] [RELAY] #2 scheduled ON in 0 ms
[271557] [RELAY] #2 set to ON
[271559] [MQTT] Sending TUYA001/relay/2 => 1 (PID 125)
[271564] [MQTT] Publish ACK for PID 125
[271566] [TUYA] =>: 55aa0006000501010001010e
[271603] [TUYA] <=: 55aa0007000501010001010f
[271603] [Tuya] Received integer dp=1 value=1[271604] [RELAY] #1 scheduled ON in 0 ms
[271605] [TUYA] <=: 55aa0007000501010001010f
[271605] [Tuya] Received integer dp=1 value=1[271605] [RELAY] #1 scheduled ON in 0 ms
[271617] [RELAY] #1 set to ON
[271619] [MQTT] Sending TUYA001/relay/1 => 1 (PID 126)
[271624] [MQTT] Publish ACK for PID 126
[271628] [TUYA] <=: 55aa00070008020200040000001026
[271629] [Tuya] Received boolean dp=2 value=#t[271629] [TUYA] =>: 55aa0006000501010001010e
[271646] [TUYA] <=: 55aa0007000501010001010f
[271647] [Tuya] Received integer dp=1 value=1[271659] [TUYA] <=: 55aa0007000802020004000000ff15
[271659] [Tuya] Received boolean dp=2 value=#t[271671] [TUYA] <=: 55aa0007000501010001010f
[271672] [Tuya] Received integer dp=1 value=1[272623] [RELAY] Relay mask: 0b110
[273452] [WEBSOCKET] Requested action: relay
[273453] [RELAY] #2 scheduled OFF in 0 ms
[273462] [RELAY] #2 set to OFF
[273464] [MQTT] Sending TUYA001/relay/2 => 0 (PID 127)
[273470] [MQTT] Publish ACK for PID 127
[273471] [TUYA] =>: 55aa0006000501010001000d
[273507] [TUYA] <=: 55aa0007000501010001000e
[273508] [Tuya] Received integer dp=1 value=0[273508] [RELAY] #1 scheduled OFF in 0 ms
[273519] [RELAY] #1 set to OFF
[273522] [MQTT] Sending TUYA001/relay/1 => 0 (PID 128)
[273527] [MQTT] Publish ACK for PID 128
[273528] [TUYA] <=: 55aa0007000501010001000e
[273528] [Tuya] Received integer dp=1 value=0[273529] [TUYA] <=: 55aa0007000802020004000000ff15
[273530] [Tuya] Received boolean dp=2 value=#t[273533] [TUYA] =>: 55aa0006000501010001000d
[273547] [TUYA] <=: 55aa0007000501010001000e
[273552] [Tuya] Received integer dp=1 value=0[273566] [TUYA] <=: 55aa00070008020200040000001026
[273566] [Tuya] Received boolean dp=2 value=#t[273567] [TUYA] <=: 55aa0007000501010001000e
[273567] [Tuya] Received integer dp=1 value=0[273727] [TUYA] =>: 55aa00000000ff
[273753] [TUYA] <=: 55aa000000010101
[274525] [RELAY] Relay mask: 0b0
```
`#0` and `#1` work as above but `#1` follows `#2` a short while after it's set either ON or OFF. Again dimming doesn't work, `channel/0` seems to be set at 0. `brightness` changes WRT the webUI but doesn't actually dim the light.

- What does now work, after a power cycle, switch `#1` is ON in the webUI and after around 5 seconds, the switch and the light go OFF. Managed to catch the following after boot:
```
[005516] [WEBSOCKET] #1 connected, ip: 192.168.1.134, url: /ws
[006143] [TUYA] Discovery finished
[006143] [TUYA] Switch for DP id=1 already exists
[006168] [RELAY] Boot mask: 0b0
[006173] [RELAY] #2 set to OFF
[006177] [TUYA] =>: 55aa0006000501010001000d
[006210] [TUYA] <=: 55aa0007000501010001000e
[006211] [Tuya] Received integer dp=1 value=0[006211] [RELAY] #1 scheduled OFF in 0 ms
[006222] [RELAY] #1 set to OFF
[006225] [MQTT] Sending TUYA001/relay/1 => 0 (PID 8)
[006230] [MQTT] Publish ACK for PID 8
[006231] [TUYA] <=: 55aa0007000501010001000e
[006231] [Tuya] Received integer dp=1 value=0[006232] [TUYA] <=: 55aa0007000802020004000000ff15
[006233] [Tuya] Received boolean dp=2 value=#t[006233] [TUYA] =>: 55aa0006000501010001000d
[006247] [TUYA] <=: 55aa0007000501010001000e
[006247] [Tuya] Received integer dp=1 value=0[006260] [TUYA] <=: 55aa00070008020200040000001026
[006260] [Tuya] Received boolean dp=2 value=#t[006272] [TUYA] <=: 55aa0007000501010001000e
[006273] [Tuya] Received integer dp=1 value=0[007228] [RELAY] Relay mask: 0b0
[012529] [TUYA] =>: 55aa00000000ff
[012555] [TUYA] <=: 55aa000000010101
```

- The phyisical button on the device controls switch `#1` and toggles the light ON/OFF.

**Comment by davebuk** [comment]
I'm not sure what 'tuya' commands are working in the debug screen but setting `set tuyaSwitch0 0` has removed the third switch and controls again with switch `#1` not `#0` and dimming doesn't work.

**Comment by davebuk** [comment]
In addition, re-uploading my presiously working .bin files has lost the ability to control the dimming. ON/OFF works but the light is on 100%. MQTT commands are being sent/received and webUI changes, but the light doesn't change.

**Comment by mcspr** [comment]
Thanks!

The idea right now is that we are not allowed to send channel values that are below 16, thus we never turn OFF the lights via global switch, only via the one marked as `tuya`. But, if we do `set tuyaChanState 1`, `set tuyaSwitch0 0` and `set tuyaChannel0 2` (so we don't create any managed switches), global lights now sends switch data after channel output is done

after channel state value is set, i'd expect it to do:
-  `=>: 55aa0006000501010001000d` for lights OFF
- `=>: 55aa00060008000200040000006679` + `=>: 55aa0006000501010001010e` right after for lights ON (note the channel value 0x66 aka 102 at the end)
- (*edit:* but, it might still be broken... just noticed MCU reports 100% brightness as `<=: 55aa0007000802020004000000ff15` :/ maybe only turning it off works correctly, turning on with channel value is enough)

`tuya.show` after discovery should show what is up with 2nd switch, my only guess I missed unique check somewhere and received the same switch twice :/

File: code/espurna/tuya.cpp [hunk 1]
```diff
@@ -27,41 +28,143 @@ Copyright (C) 2019 by Maxim Prokhorov <prokhorov dot max at outlook dot com>
...
+            if (!dp) {
+                return;
+            }
+
+            // tuya dimmer is precious, and can't handle 0...some-kind-of-threshold
+            // just ignore it, the associated switch will handle turning it off
+            auto rounded = static_cast<unsigned int>(value);
+            if (rounded <= 0x10) {
+                return;
+            }
```
Comment (mcspr) [inline code/espurna/tuya.cpp:152]: Basically, it simply skips any value less than 16 (aka 0x10). This is based on the return value from the dimmer which seemed to stop right after this threshold.

**Comment by mcspr** [comment]
One more thing... There is `set dbgLogBuf 1` which should record everything that happens between boot and webui access:
https://github.com/xoseperez/espurna/blob/6141cc2b5a6b9fd3db19342167546bb88c833fc7/code/espurna/debug.cpp#L402-L403
(default size is 4096, which should be enough to catch discovery messages, unless those are really chatty)

`debug.buffer` terminal command will print the log

**Comment by davebuk** [comment]
1.15.0-dev (c1d19647)

- After first boot I ran: `set tuyaChanState 1`, `set tuyaSwitch0 0` and `set tuyaChannel0 2`.

- Only two switches are defined and ON/OFF of them one after the other gives:
```
[151635] [WEBSOCKET] Requested action: relay
[151636] [RELAY] #0 scheduled ON in 0 ms
[151646] [RELAY] #0 set to ON
[151648] [MQTT] Sending TUYA001/relay/0 => 1 (PID 29)
[151659] [MQTT] Publish ACK for PID 29
[151748] [MQTT] Sending TUYA001/channel/0 => 102 (PID 30)
[151749] [MQTT] Sending TUYA001/brightness => 255 (PID 31)
[151754] [MQTT] Publish ACK for PID 30
[151768] [MQTT] Publish ACK for PID 31
[152154] [TUYA] =>: 55aa00060008000200040000006679
[152653] [RELAY] Relay mask: 0b1
[153267] [WEBSOCKET] Requested action: relay
[153268] [RELAY] #0 scheduled OFF in 0 ms
[153281] [RELAY] #0 set to OFF
[153283] [MQTT] Sending TUYA001/relay/0 => 0 (PID 32)
[153286] [MQTT] Publish ACK for PID 32
[153384] [MQTT] Sending TUYA001/channel/0 => 0 (PID 33)
[153385] [MQTT] Sending TUYA001/brightness => 255 (PID 34)
[153390] [MQTT] Publish ACK for PID 33
[153393] [MQTT] Publish ACK for PID 34
[153791] [TUYA] =>: 55aa0006000501010001000d
[153826] [TUYA] <=: 55aa0007000501010001000e
[154289] [RELAY] Relay mask: 0b0
[154732] [WEBSOCKET] Requested action: relay
[154733] [RELAY] #1 scheduled ON in 0 ms
[154738] [RELAY] #1 set to ON
[154740] [MQTT] Sending TUYA001/relay/1 => 1 (PID 35)
[154743] [MQTT] Publish ACK for PID 35
[154747] [TUYA] =>: 55aa0006000501010001010e
[154783] [TUYA] <=: 55aa0007000501010001010f
[154784] [RELAY] #0 scheduled ON in 0 ms
[154795] [RELAY] #0 set to ON
[154797] [MQTT] Sending TUYA001/relay/0 => 1 (PID 36)
[154802] [MQTT] Publish ACK for PID 36
[154805] [TUYA] <=: 55aa0007000501010001010f
[154806] [TUYA] <=: 55aa00070008020200040000001026
[154821] [TUYA] <=: 55aa0007000501010001010f
[154834] [TUYA] <=: 55aa0007000802020004000000ff15
[154897] [MQTT] Sending TUYA001/channel/0 => 102 (PID 37)
[154898] [MQTT] Sending TUYA001/brightness => 255 (PID 38)
[154911] [MQTT] Publish ACK for PID 37
[154916] [MQTT] Publish ACK for PID 38
[155302] [TUYA] =>: 55aa00060008000200040000006679
[155800] [RELAY] Relay mask: 0b11
[156436] [WEBSOCKET] Requested action: relay
[156437] [RELAY] #1 scheduled OFF in 0 ms
[156446] [RELAY] #1 set to OFF
[156448] [MQTT] Sending TUYA001/relay/1 => 0 (PID 39)
[156451] [MQTT] Publish ACK for PID 39
[156456] [TUYA] =>: 55aa0006000501010001000d
[156492] [TUYA] <=: 55aa0007000501010001000e
[156492] [RELAY] #0 scheduled OFF in 0 ms
[156504] [RELAY] #0 set to OFF
[156508] [MQTT] Sending TUYA001/relay/0 => 0 (PID 40)
[156512] [MQTT] Publish ACK for PID 40
[156515] [TUYA] <=: 55aa0007000501010001000e
[156517] [TUYA] <=: 55aa0007000802020004000000ff15
[156534] [TUYA] <=: 55aa0007000501010001000e
[156546] [TUYA] <=: 55aa00070008020200040000001026
[156608] [MQTT] Sending TUYA001/channel/0 => 0 (PID 41)
[156609] [MQTT] Sending TUYA001/brightness => 255 (PID 42)
[156613] [MQTT] Publish ACK for PID 41
[156618] [TUYA] =>: 55aa00000000ff
[156620] [MQTT] Publish ACK for PID 42
[156643] [TUYA] <=: 55aa000000010101
[157009] [TUYA] =>: 55aa0006000501010001000d
[157045] [TUYA] <=: 55aa0007000501010001000e
[157511] [RELAY] Relay mask: 0b0
```
Same as before, light is turned ON/OFF by switch `#1` which also cycles switch `#0`. Again, dimming doesn't work and the light is at 100% brightness.

- I `set dbgLogBuf 1` and did a restart, but `debug.buffer` just reports `Buffer is empty`. Do I need to run a save command to confirm these settings are saved?

**Comment by davebuk** [comment]
- `keys` _reduced_ shows:

```
> boardName => "TUYA_GENERIC_DIMMER"
> brightness => "255"
> btnGPIO0 => "0"
> btnRepDel => "500"
> cfg => "5"
> ch0 => "131"
> ch1 => "164"
> dbgLogBuf => "1"
> relayBoot0 => "2"
> relayBootMask => "0b0"
> tuyaChanState => "1"
> tuyaChannel0 => "2"
> tuyaFilter => "2"
> tuyaSwitch0 => "0"
> tuyafilter => "2"
```
- `tuya.show` gives:
```
Config:
"btnGPIO0" => "0""ledGPIO0" => "14"
Known DP(s):
1 (bool) => lights state
2 (int) => 0 (channel)
1 (bool) => 1 (relay)
```

**Comment by mcspr** [comment]
Log buffer should work, discovery should not create a 2nd switch. 

> [154805] [TUYA] <=: 55aa0007000501010001010f
[154806] [TUYA] <=: 55aa00070008020200040000001026
[154821] [TUYA] <=: 55aa0007000501010001010f
[154834] [TUYA] <=: 55aa0007000802020004000000ff15
> ...
> [155302] [TUYA] =>: 55aa00060008000200040000006679
> ...
> 2 (int) => 0 (channel)

I also just noticed outgoing message... also fixed the channel ID being sent instead of the DP ID

> "ledGPIO0" => "14"

Does the LED work btw? Either `tuya.save` or manually setting the led GPIO key

**Comment by davebuk** [comment]
- 1.15.0-dev (6141cc2b)

I'm not at home to see the light or LED at the moment but debug gives the following (WiFi removed):
```
[120595] [WEBSOCKET] Requested action: dbgcmd
[120601] [DEBUG] Buffer size: 4091 / 4096 bytes
[000120] [TELNET] Listening on port 23
[000123] [WEBSERVER] Webserver running on port 80
[000126] [LIGHT] LIGHT_PROVIDER = 3
[000126] [LIGHT] Number of channels: 0
[000145] [RELAY] Boot mask: 0b0
[000146] [RELAY] #0 set to OFF
[000147] [RELAY] Number of relays: 1
[000173] [BUTTON] Number of buttons: 1
[000179] [LED] Number of leds: 1
[000180] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000180] [MQTT] Client DISABLED, DISCONNECTED
[000200] [NTP] Startup delay: 4s, Update delay: 3267s
[000209] [NTP] Server: pool.ntp.org, TZ: CET0CEST,M3.5.0,M10.5.0/3
[000215] [THINGSPEAK] Async ENABLED, SSL DISABLED
[000331] [RELAY] Boot mask: 0b0
[000332] [LIGHT] Number of channels: 1
[000339] [WIFI] Scanning
[000340] [RELAY] #0 set to OFF
[000846] [TUYA] =>: 55aa0006000501010001000d
[000879] [TUYA] <=: 55aa0007000501010001000e
[001341] [RELAY] Relay mask: 0b0
[003534] [TUYA] =>: 55aa00000000ff
[003557] [TUYA] <=: 55aa000000010101
[003557] [TUYA] Starting configuration ...
[003558] [TUYA] =>: 55aa0001000000
[003574] [MDNS] OK
[004575] [MQTT] MQTT brokers found: 0
[004580] [TUYA] <=: 55aa000100156253585353464172564b746334447943312e302e305a
[004580] [TUYA] Product: bSXSSFArVKtc4DyC1.0.0
[004581] [TUYA] =>: 55aa0002000001
[004602] [TUYA] <=: 55aa000200020e0011
[004603] [TUYA] Mode: ESP only, led=GPIO14 rst=GPIO00
[004603] [TUYA] Starting discovery
[004603] [TUYA] =>: 55aa0008000007
[004625] [TUYA] <=: 55aa0007000501010001000e
[004647] [TUYA] <=: 55aa00070008020200040000001026
[005003] [MQTT] Connecting to broker at 192.168.1.222:1883
[005003] [MQTT] Client ID: TUYA-001
[005004] [MQTT] QoS: 1
[005004] [MQTT] Retain flag: 1
[005004] [MQTT] Keepalive time: 300s
[005004] [MQTT] Will topic: TUYA001/status
[120621] [TUYA] =>: 55aa00000000ff
```
- I still have two buttons and `tuya.show` gives:
```
Config:
"btnGPIO0" => "0"
"ledGPIO0" => "14"

Known DP(s):
1 (bool) => lights state
2 (int) => 0 (channel)
1 (bool) => 1 (relay)
```
Am I meant to run additional commands to bind the two switches?

**Comment by mcspr** [comment]
> Am I meant to run additional commands to bind the two switches?

There should only be a single switch via lights. https://github.com/xoseperez/espurna/pull/2414/commits/69f72a4d28a3138473f3776e96053e85a620f926 should set the settings (finally) as the definitive source of the DP associations, what I missed is the switches config setting discovery back to ON again.

**Comment by davebuk** [comment]
Looking good, nice work!
- 1.15.0-dev (69f72a4d)

`debug.buffer` now gives:
```
[134314] [WEBSOCKET] Requested action: dbgcmd
[134320] [DEBUG] Buffer size: 4036 / 4096 bytes
[000118] [TELNET] Listening on port 23
[000121] [WEBSERVER] Webserver running on port 80
[000124] [LIGHT] LIGHT_PROVIDER = 3
[000125] [LIGHT] Number of channels: 0
[000146] [RELAY] Boot mask: 0b0
[000147] [RELAY] #0 set to OFF
[000148] [RELAY] Number of relays: 1
[000173] [BUTTON] Number of buttons: 1
[000179] [LED] Number of leds: 1
[000180] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000181] [MQTT] Client DISABLED, DISCONNECTED
[000201] [NTP] Startup delay: 5s, Update delay: 1925s
[000209] [NTP] Server: pool.ntp.org, TZ: CET0CEST,M3.5.0,M10.5.0/3
[000216] [THINGSPEAK] Async ENABLED, SSL DISABLED
[000332] [RELAY] Boot mask: 0b0
[000333] [LIGHT] Number of channels: 1
[000342] [WIFI] Scanning
[000343] [RELAY] #0 set to OFF
[000849] [TUYA] =>: 55aa0006000501010001000d
[000953] [TUYA] <=: 55aa0007000501010001010f
[000954] [RELAY] #0 scheduled ON in 0 ms
[000965] [RELAY] #0 set to ON
[000968] [TUYA] <=: 55aa0007000802020004000000ff15
[001474] [TUYA] =>: 55aa0006000802020004000000667b
[001516] [TUYA] <=: 55aa0007000802020004000000667c
[001528] [TUYA] <=: 55aa0007000501010001010f
[001539] [TUYA] <=: 55aa0007000802020004000000758b
[001968] [RELAY] Relay mask: 0b1
[003506] [TUYA] =>: 55aa00000000ff
[003529] [TUYA] <=: 55aa000000010000
[003530] [TUYA] Starting configuration ...
[003530] [TUYA] =>: 55aa0001000000
[003541] [WIFI] Captive portal disabled
[003542] [WIFI] ------------------------------------- MODE STA
[004548] [MQTT] MQTT brokers found: 0
[004553] [TUYA] <=: 55aa000100156253585353464172564b746334447943312e302e305a
[004553] [TUYA] Product: bSXSSFArVKtc4DyC1.0.0
[004554] [TUYA] =>: 55aa0002000001
[004581] [TUYA] <=: 55aa000200020e0011
[004581] [TUYA] Mode: ESP only, led=GPIO14 rst=GPIO00
[004581] [TUYA] Starting discovery
[004582] [TUYA] =>: 55aa0008000007
[004604] [TUYA] <=: 55aa0007000501010001010f
[004627] [TUYA] <=: 55aa0007000802020004000000758b
[005004] [MQTT] Connecting to broker at 192.168.1.222:1883
[005004] [MQTT] Client ID: TUYA-001
[005004] [MQTT] QoS: 1
[005004] [MQTT] Retain flag: 1
[005005] [MQTT] Keepalive time: 300s
[005005] [MQTT] Will topic: TUYA001/status
[005015] [MQTT] Connected!
[005016] [MQTT] Unsubscribing to # (PID 1)
[005017] [MQTT] Subscribing to TUYA001/brightness/set (PID 2)
[005018] [MQTT] Subscribing to TUYA001/channel/+/set (PID 3)
[005018] [MQTT] Subscribing to TUYA001/relay/+/set (PID 4)
[138599] [TUYA] =>: 55aa00000000ff
[138624] [TUYA] <=: 55aa000000010101
[147606] [TUYA] =>: 55aa00000000ff
[147631] [TUYA] <=: 55aa000000010101
[156616] [TUYA] =>: 55aa00000000ff
[156642] [TUYA] <=: 55aa000000010101
```

`tuya.show gives`:
```
Config:
"btnGPIO0" => "0"
"ledGPIO0" => "14"

Known DP(s):
1 (bool) => lights state
2 (int) => 0 (channel)
```
- There is now only one switch which is controllable via webUI and MQTT.
- Dimming now works. It works better than before as it doesn't flick the brightness as referenced in #2222 it just turns ON straight to the previous value. Yes, a transition up to and down down that value would be really nice, but that's for another issue.
- With LED undefined in webUI, the RED LED follows the ON/OFF state. With the LED defined, the GREEN LED is used and over illuminates the RED. As the relay goes OFF, the GREEN goes OFF then half a second later the RED goes OFF.

The only issue I can see is that after a mains power cycle, the switch/relay is back to turning ON. `Channel#0` is shown as 0 but the light brightness is actually the value before turning OFF. Previous testing, the relay went back to OFF after a few seconds which now isn't working again. However, the relay status does represent this so the webUI and MQTT shows the status as ON and can be turned OFF using either method.

- `Keys` after setting Channel#0 shows: 
```
> ch0 => "255"
> ch1 => "164" 
```
- `Keys` after `REBOOT` or power cycle, Channel#0 shows: 
```
> ch0 => "0"
> ch1 => "164"
```

**Comment by mcspr** [comment]
Does it receive some kind of MQTT payload after the log is done?
Does it behave differently without the relay boot mode set to 'Same as before'? Tuya side does not touch channel / brightness values, but maybe something manages to save settings when lights are not yet configured correctly
What are the lights settings? (besides just printing all `keys`, you can also go to the LIGHTS panel and enter in the address  `javascript:$(".hint").hide()` + hit ENTER, then screenshot the result)

> Yes, a transition up to and down down that value would be really nice, but that's for another issue.

Transitions are implemented btw, but disabled by default. ON / OFF is  'Color transitions' at the bottom of the WebUI panel, total time + step time are there as well

**Comment by mcspr** [comment]
Yeah, nvm about the mqtt, I think I found the issue with the order of operations when relay boot mode is set

**Comment by davebuk** [comment]
You could be correct about MQTT. I have an openHAB rule that, after two seconds of receiving an update to the switch topic of ON, set brightness to 40%. I have just tried with the rule disabled and set to 5 seconds and the relay/switch stays in the OFF position and previous CH#0 value after a `REBOOT`. Can't try a mains power cycle at the moment.

I did try the colour transition settings yesterday, but it didn't seem to work. I'll give it another go later. I tried changing the value from 500ms to 1500ms but it doesn't seem to be saving the value. It says 'saved' but after a refresh, the webUI goes back to 500ms. the `key` for `lightTime` shows 500 (which I guess is that value).

File: code/html/index.html [hunk 2]
```diff
@@ -621,15 +626,23 @@ <h2>Lights configuration</h2>
...
+                                    <div class="pure-u-1 pure-u-lg-3-4 hint">Time to transition from one color to another (ms)</div>
+                                </div>
+
+                                <div class="pure-g">
+                                    <label class="pure-u-1 pure-u-lg-1-4">Transition step</label>
+                                    <div class="pure-u-1 pure-u-lg-1-4"><input class="pure-u-1" type="number" name="ltStep" min="10" max="5000" tabindex="15" action="reload" /></div>
                                     <div class="pure-u-0 pure-u-lg-1-2"></div>
                                     <div class="pure-u-0 pure-u-lg-1-4"></div>
-                                    <div class="pure-u-1 pure-u-lg-3-4 hint">Time in millisecons to transition from one color to another.</div>
+                                    <div class="pure-u-1 pure-u-lg-3-4 hint">(ms, depends on the transition time)</div>
```
Comment (mcspr) [inline code/html/index.html:664]: this patch renames `lightTime` -> `ltTime`
`ltStep` is a new one

Comment (davebuk) [reply code/html/index.html:664]: 1.15.0-dev (8cfe7032) transition time still not saving or showing up in `keys`.

**Comment by davebuk** [comment]
- Light transition settings are now saving but the defaults of 500ms for transition and steps still 'steps' the light to the value required. If I set the step to 100ms (which I presume over 500ms it should do 5 steps every 100ms) the relay doesn't stay OFF when selected from ON to OFF. It seems to try and step down the brightness towards OFF but straight away turns back ON and stays on. If the two values are the same (e.g both 500, 1000 or 1500 etc) the light goes OFF but doesn't reduce in brightness slowly, it just goes OFF. Following is when time/set is 500/100 and selected to ON from OFF.
```
[611998] [WEBSOCKET] Requested action: relay
[611999] [RELAY] #0 scheduled OFF in 0 ms
[612002] [RELAY] #0 set to OFF
[612004] [MQTT] Sending TUYA001/relay/0 => 0 (PID 1)
[612105] [MQTT] Sending TUYA001/channel/0 => 0 (PID 1)
[612106] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[612114] [TUYA] =>: 55aa00060008020200040000005368
[612148] [TUYA] <=: 55aa00070008020200040000005369
[612163] [TUYA] <=: 55aa0007000501010001010f
[612166] [RELAY] #0 scheduled ON in 0 ms
[612180] [RELAY] #0 set to ON
[612182] [MQTT] Sending TUYA001/relay/0 => 1 (PID 1)
[612187] [TUYA] <=: 55aa00070008020200040000006278
[612282] [MQTT] Sending TUYA001/channel/0 => 104 (PID 1)
[612283] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[612293] [TUYA] =>: 55aa0006000802020004000000576c
[612327] [TUYA] <=: 55aa0007000802020004000000576d
```

- After mains power cycle, relay is still turning ON by itself. `debug.buffer` shows (reduced):
```
[611998] [WEBSOCKET] Requested action: relay
[611999] [RELAY] #0 scheduled OFF in 0 ms
[612002] [RELAY] #0 set to OFF
[612004] [MQTT] Sending TUYA001/relay/0 => 0 (PID 1)
[612105] [MQTT] Sending TUYA001/channel/0 => 0 (PID 1)
[612106] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[612114] [TUYA] =>: 55aa00060008020200040000005368
[612148] [TUYA] <=: 55aa00070008020200040000005369
[612163] [TUYA] <=: 55aa0007000501010001010f
[612166] [RELAY] #0 scheduled ON in 0 ms
[612180] [RELAY] #0 set to ON
[612182] [MQTT] Sending TUYA001/relay/0 => 1 (PID 1)
[612187] [TUYA] <=: 55aa00070008020200040000006278
[612282] [MQTT] Sending TUYA001/channel/0 => 104 (PID 1)
[612283] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[612293] [TUYA] =>: 55aa0006000802020004000000576c
[612327] [TUYA] <=: 55aa0007000802020004000000576d
```

But after a `REBOOT` I get:
```
[020747] [WEBSOCKET] Requested action: dbgcmd
[020749] [DEBUG] Buffer size: 4069 / 4096 bytes
[000119] [TELNET] Listening on port 23
[000122] [WEBSERVER] Webserver running on port 80
[000127] [LIGHT] LIGHT_PROVIDER = 3
[000127] [LIGHT] Number of channels: 0
[000147] [RELAY] Number of relays: 1, boot mask: 0b1
[000147] [RELAY] #0 set to OFF
[000174] [BUTTON] Number of buttons: 1
[000180] [LED] Number of leds: 1
[000181] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000181] [MQTT] Client DISABLED, DISCONNECTED
[000332] [RELAY] Number of relays: 1, boot mask: 0b1
[000333] [LIGHT] Number of channels: 1
[000341] [WIFI] Scanning
[000341] [RELAY] #0 set to OFF
[000847] [TUYA] =>: 55aa0006000501010001000d
[000880] [TUYA] <=: 55aa0007000501010001000e
[000892] [TUYA] <=: 55aa0007000501010001000e
[000904] [TUYA] <=: 55aa00070008020200040000006a80
[000916] [TUYA] <=: 55aa0007000501010001000e
[000937] [TUYA] <=: 55aa00070008020200040000001026
[001342] [RELAY] Relay mask: 0b0
[003494] [TUYA] =>: 55aa00000000ff
[003516] [TUYA] <=: 55aa000000010101
[003516] [TUYA] Already configured
[004618] [MDNS] OK
[021512] [TUYA] =>: 55aa00000000ff
[021537] [TUYA] <=: 55aa000000010101
```

**Comment by mcspr** [comment]
https://github.com/xoseperez/espurna/pull/2414/commits/3fa5ee0878f38fb0a357eb1eb63d7ff7a4afcbc6 should avoid reading incoming relay state, so it does not sync while transition is happening.

I'd also be a bit wary of timing, ~200 step and 1000ms total might be safer? MCU does send state twice, and looking at some logs it sometimes sends completely different things right after the other, so idk how it might behave when things happen too fast for it.

**Comment by davebuk** [comment]
Transitions are working. Its not smooth like an LED but works. Using 1000ms, 100ms step.

- Going from OFF to ON, previously 100% the output is:
```
[877743] [MQTT] Received TUYA001/relay/0/set => 1
[877746] [RELAY] #0 scheduled ON in 0 ms
[877749] [RELAY] #0 set to ON
[877752] [MQTT] Sending TUYA001/relay/0 => 1 (PID 1)
[877852] [MQTT] Sending TUYA001/channel/0 => 255 (PID 1)
[877853] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[877859] [TUYA] =>: 55aa0006000802020004000000192e
[877893] [TUYA] <=: 55aa0007000802020004000000192f
[877905] [TUYA] <=: 55aa0007000501010001010f
[877930] [TUYA] <=: 55aa00070008020200040000003a50
[877964] [TUYA] =>: 55aa00060008020200040000003348
[878000] [TUYA] <=: 55aa00070008020200040000003349
[878014] [TUYA] <=: 55aa0007000501010001010f
[878029] [TUYA] <=: 55aa00070008020200040000004359
[878074] [TUYA] =>: 55aa00060008020200040000004c61
[878109] [TUYA] <=: 55aa00070008020200040000004c62
[878124] [TUYA] <=: 55aa0007000501010001010f
[878138] [TUYA] <=: 55aa00070008020200040000005c72
[878184] [TUYA] =>: 55aa0006000802020004000000667b
[878220] [TUYA] <=: 55aa0007000802020004000000667c
[878232] [TUYA] <=: 55aa0007000501010001010f
[878245] [TUYA] <=: 55aa0007000802020004000000758b
[878295] [TUYA] =>: 55aa00060008020200040000007f94
[878329] [TUYA] <=: 55aa00070008020200040000007f95
[878341] [TUYA] <=: 55aa0007000501010001010f
[878366] [TUYA] <=: 55aa00070008020200040000008ea4
[878401] [TUYA] =>: 55aa000600080202000400000099ae
[878436] [TUYA] <=: 55aa000700080202000400000099af
[878450] [TUYA] <=: 55aa0007000501010001010f
[878464] [TUYA] <=: 55aa0007000802020004000000a8be
[878510] [TUYA] =>: 55aa0006000802020004000000b2c7
[878546] [TUYA] <=: 55aa0007000802020004000000b2c8
[878560] [TUYA] <=: 55aa0007000501010001010f
[878574] [TUYA] <=: 55aa0007000802020004000000c1d7
[878620] [TUYA] =>: 55aa0006000802020004000000cce1
[878656] [TUYA] <=: 55aa0007000802020004000000cce2
[878669] [TUYA] <=: 55aa0007000501010001010f
[878684] [TUYA] <=: 55aa0007000802020004000000daf0
[878730] [TUYA] =>: 55aa0006000802020004000000e5fa
[878754] [RELAY] Relay mask: 0b1
[878768] [TUYA] <=: 55aa0007000802020004000000e5fb
[878783] [TUYA] <=: 55aa0007000501010001010f
[878797] [TUYA] <=: 55aa0007000802020004000000f309
[878833] [TUYA] =>: 55aa0006000802020004000000ff14
[878868] [TUYA] <=: 55aa0007000802020004000000ff15
[878882] [TUYA] <=: 55aa0007000501010001010f
[878896] [TUYA] <=: 55aa0007000802020004000000ff15
[881702] [TUYA] =>: 55aa00000000ff
[881727] [TUYA] <=: 55aa000000010101
[890711] [TUYA] =>: 55aa00000000ff
[890736] [TUYA] <=: 55aa000000010101
```
- Going from ON at 100% to OFF gives:
```
[947968] [MQTT] Received TUYA001/relay/0/set => 0
[947970] [RELAY] #0 scheduled OFF in 0 ms
[947978] [RELAY] #0 set to OFF
[947981] [MQTT] Sending TUYA001/relay/0 => 0 (PID 1)
[948081] [MQTT] Sending TUYA001/channel/0 => 0 (PID 1)
[948082] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[948090] [TUYA] =>: 55aa0006000802020004000000e5fa
[948124] [TUYA] <=: 55aa0007000802020004000000e5fb
[948136] [TUYA] <=: 55aa0007000501010001010f
[948161] [TUYA] <=: 55aa0007000802020004000000f309
[948186] [TUYA] =>: 55aa0006000802020004000000cce1
[948222] [TUYA] <=: 55aa0007000802020004000000cce2
[948234] [TUYA] <=: 55aa0007000501010001010f
[948257] [TUYA] <=: 55aa0007000802020004000000daf0
[948293] [TUYA] =>: 55aa0006000802020004000000b2c7
[948328] [TUYA] <=: 55aa0007000802020004000000b2c8
[948342] [TUYA] <=: 55aa0007000501010001010f
[948357] [TUYA] <=: 55aa0007000802020004000000c1d7
[948402] [TUYA] =>: 55aa000600080202000400000099ae
[948437] [TUYA] <=: 55aa000700080202000400000099af
[948451] [TUYA] <=: 55aa0007000501010001010f
[948468] [TUYA] <=: 55aa0007000802020004000000a8be
[948503] [TUYA] =>: 55aa00060008020200040000007f94
[948538] [TUYA] <=: 55aa00070008020200040000007f95
[948552] [TUYA] <=: 55aa0007000501010001010f
[948567] [TUYA] <=: 55aa00070008020200040000008ea4
[948612] [TUYA] =>: 55aa0006000802020004000000667b
[948648] [TUYA] <=: 55aa0007000802020004000000667c
[948661] [TUYA] <=: 55aa0007000501010001010f
[948677] [TUYA] <=: 55aa0007000802020004000000758b
[948713] [TUYA] =>: 55aa00060008020200040000004c61
[948748] [TUYA] <=: 55aa00070008020200040000004c62
[948762] [TUYA] <=: 55aa0007000501010001010f
[948777] [TUYA] <=: 55aa00070008020200040000005c72
[948823] [TUYA] =>: 55aa00060008020200040000003348
[948858] [TUYA] <=: 55aa00070008020200040000003349
[948873] [TUYA] <=: 55aa0007000501010001010f
[948888] [TUYA] <=: 55aa00070008020200040000004359
[948924] [TUYA] =>: 55aa0006000802020004000000192e
[948959] [TUYA] <=: 55aa0007000802020004000000192f
[948974] [TUYA] <=: 55aa0007000501010001010f
[948983] [RELAY] Relay mask: 0b0
[948989] [TUYA] <=: 55aa00070008020200040000003a50
[949024] [TUYA] =>: 55aa0006000501010001000d
[949059] [TUYA] <=: 55aa0007000501010001000e
[949073] [TUYA] <=: 55aa0007000501010001000e
[949088] [TUYA] <=: 55aa00070008020200040000003a50
[949102] [TUYA] <=: 55aa0007000501010001000e
[949115] [TUYA] <=: 55aa00070008020200040000001026
```

- Unfortunately, the light is still returning to ON after a mains power cycle. I have turned my MQTT dimming rule OFF, set QOS to 0 and turned retain OFF.

- Its not something I've really looked at before, but going from around 60% to 100%, there doesn't seem to be much change in actual brightness of the connected light. The following is without transitions on, going from 50% to 80% via MQTT:
```
[422016] [TUYA] =>: 55aa00000000ff
[422041] [TUYA] <=: 55aa000000010101
[423965] [MQTT] Received TUYA001/channel/0/set => 140.25
[424070] [MQTT] Sending TUYA001/channel/0 => 140 (PID 1)
[424070] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[424081] [TUYA] =>: 55aa00060008020200040000008ca1
[424114] [TUYA] <=: 55aa00070008020200040000008ca2
[424128] [TUYA] <=: 55aa0007000501010001010f
[424144] [TUYA] <=: 55aa00070008020200040000009cb2
[425997] [MQTT] Received TUYA001/channel/0/set => 153
[426101] [MQTT] Sending TUYA001/channel/0 => 153 (PID 1)
[426102] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[426108] [TUYA] =>: 55aa000600080202000400000099ae
[426141] [TUYA] <=: 55aa000700080202000400000099af
[426153] [TUYA] <=: 55aa0007000501010001010f
[426169] [TUYA] <=: 55aa0007000802020004000000a8be
[426950] [MQTT] Received TUYA001/channel/0/set => 165.75
[427055] [MQTT] Sending TUYA001/channel/0 => 165 (PID 1)
[427055] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[427066] [TUYA] =>: 55aa0006000802020004000000a5ba
[427099] [TUYA] <=: 55aa0007000802020004000000a5bb
[427112] [TUYA] <=: 55aa0007000501010001010f
[427127] [TUYA] <=: 55aa0007000802020004000000b3c9
[427840] [MQTT] Received TUYA001/channel/0/set => 178.5
[427944] [MQTT] Sending TUYA001/channel/0 => 178 (PID 1)
[427945] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[427955] [TUYA] =>: 55aa0006000802020004000000b2c7
[427988] [TUYA] <=: 55aa0007000802020004000000b2c8
[428001] [TUYA] <=: 55aa0007000501010001010f
[428025] [TUYA] <=: 55aa0007000802020004000000c1d7
[430538] [MQTT] Received TUYA001/channel/0/set => 191.25
[430642] [MQTT] Sending TUYA001/channel/0 => 191 (PID 1)
[430643] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[430659] [TUYA] =>: 55aa0006000802020004000000bfd4
[430693] [TUYA] <=: 55aa0007000802020004000000bfd5
[430705] [TUYA] <=: 55aa0007000501010001010f
[430730] [TUYA] <=: 55aa0007000802020004000000cfe5
[431021] [TUYA] =>: 55aa00000000ff
[431046] [TUYA] <=: 55aa000000010101
[431172] [MQTT] Received TUYA001/channel/0/set => 204
[431276] [MQTT] Sending TUYA001/channel/0 => 204 (PID 1)
[431276] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[431288] [TUYA] =>: 55aa0006000802020004000000cce1
[431321] [TUYA] <=: 55aa0007000802020004000000cce2
[431333] [TUYA] <=: 55aa0007000501010001010f
[431349] [TUYA] <=: 55aa0007000802020004000000daf0
```

**Comment by mcspr** [comment]
>  Its not smooth like an LED but works. Using 1000ms, 100ms step.

PWM step is 10ms... Baud-rate is main limiting factor, as it takes ~15ms to even send the channel message, plus taking into account the response echo + switch data. Unless there's some magic custom function doing the transition on-device (which is not announced via 'discovery', so we don't really know), not much more we could really do

> Unfortunately, the light is still returning to ON after a mains power cycle. I have turned my MQTT dimming rule OFF, set QOS to 0 and turned retain OFF.

Reading boot logs above, it actually sends ON on boot:
```
[000343] [RELAY] #0 set to OFF
[000849] [TUYA] =>: 55aa0006000501010001000d <--- we sending OFF (2nd to last byte)
[000953] [TUYA] <=: 55aa0007000501010001010f  <--- immediately receiving ON
[000954] [RELAY] #0 scheduled ON in 0 ms
[000965] [RELAY] #0 set to ON
```

But, sometimes it does not:
```
000340] [RELAY] #0 set to OFF
[000846] [TUYA] =>: 55aa0006000501010001000d <--- sending OFF
[000879] [TUYA] <=: 55aa0007000501010001000e <--- ...receiving OFF
```
I vaguely remember the previous issue, but aren't there 2 buttons? GPIO0-one (...that will just send the relay command) and the physical switch holding the 'state'? Or maybe channel values need to be zeroed out as well. Unless those are random values sent on boot though, if everything else works as expected I could try adding comparison with our state and ignore otherwise if the switch does nothing with the state

**Comment by davebuk** [comment]
Ref transitions, that makes sense. The rate is limited by the hardware, not espurna. I think it's fine as it currently stands.

The two snippets of code above I believe are from the two different reboot triggers. The one that is fine is using `REBOOT` from the webUI, the other is a cold boot after a 240VAC power cycle. https://github.com/xoseperez/espurna/pull/2414/commits/3fea207f723887a230118a76a0d5efcef785b9da seemed to work in the fact that a few seconds after a cold boot, the switch turned from ON to OFF.

The physical device only has one momentary button. Just looking at `hardware.h` the button doesn't seem to be defined. Should it be and bind it to the relay?

File: code/espurna/tuya_util.h [hunk 3]
```diff
@@ -12,114 +12,186 @@ Copyright (C) 2019 by Maxim Prokhorov <prokhorov dot max at outlook dot com>
...
+        return *this;
+    }
+
+    explicit operator bool() {
+        return _id != 0u;
+    }
+
+private:
+    uint8_t _id { 0 };
+    bool _filter { false };
```
Comment (mcspr) [inline code/espurna/tuya_util.h:61]: For cold boot issue specifically
```suggestion
    bool _filter { true };
```
I wonder if this will work. This way it will ignore incoming value up until both relay and channel statuses are set

Comment (davebuk) [reply code/espurna/tuya_util.h:61]: Yep, that fixed it! After cold boot the light comes ON for about a second, then returns to OFF. `debug.buffer` gives:
```
[042390] [WEBSOCKET] Requested action: dbgcmd
[042395] [DEBUG] Buffer size: 4084 / 4096 bytes
[000127] [LIGHT] LIGHT_PROVIDER = 3
[000128] [LIGHT] Number of channels: 0
[000150] [RELAY] Number of relays: 1, boot mask: 0b1
[000150] [RELAY] #0 set to OFF
[000177] [BUTTON] Number of buttons: 1
[000183] [LED] Number of leds: 1
[000336] [RELAY] Number of relays: 1, boot mask: 0b1
[000337] [LIGHT] Number of channels: 1
[000347] [WIFI] Scanning
[000347] [RELAY] #0 set to OFF
[000957] [TUYA] <=: 55aa0007000501010001010f
[000969] [TUYA] <=: 55aa0007000802020004000000ff15
[001348] [RELAY] Relay mask: 0b0
[001983] [TUYA] =>: 55aa0006000501010001000d
[002015] [TUYA] <=: 55aa0007000501010001000e
[002026] [TUYA] <=: 55aa0007000501010001000e
[002038] [TUYA] <=: 55aa0007000802020004000000ff15
[002059] [TUYA] <=: 55aa0007000501010001000e
[002071] [TUYA] <=: 55aa00070008020200040000001026
[003502] [TUYA] =>: 55aa00000000ff
[042527] [TUYA] =>: 55aa00000000ff
[042552] [TUYA] <=: 55aa000000010101
```

Comment (mcspr) [reply code/espurna/tuya_util.h:61]: Hm. MCU turns the lights ON after ~1s all by itself though...
Just to understand wth it's doing, what happens after disabling transitions and commenting out `// updateSwitch(proto);` here? Meaning, at around ~400ms we should send OFF, but never parse the incoming ON.
https://github.com/xoseperez/espurna/blob/3fa5ee0878f38fb0a357eb1eb63d7ff7a4afcbc6/code/espurna/tuya.cpp#L264

BTW, the 1s wait comes from the lights engine doing the whole 'steps' routine without ever checking that the channel value changes between each step, since we only ever get the final `=>: 55aa0006000501010001000d` after transition timer expires and does the 10th step. In earlier examples it waits exactly 500ms (`ltStep` default), right now it's 100ms. Will need to fix that

Comment (davebuk) [reply code/espurna/tuya_util.h:61]: Neither of the changes turn the light back OFF after a cold boot if transitions are turned OFF. The values are currently set (for no real reason) to 1600/200ms which works quite well when going from 0-100% and back.

The two videos show the LED state when re-applying mains power.

https://user-images.githubusercontent.com/3661426/104120516-6c459580-532f-11eb-839e-ba8ae1b3757c.mp4

https://user-images.githubusercontent.com/3661426/104120518-6d76c280-532f-11eb-8b65-013aea786913.mp4

Comment (mcspr) [reply code/espurna/tuya_util.h:61]: Why 1 second though :/ https://github.com/xoseperez/espurna/pull/2414/commits/24870953b6dfead1e9fd26265213c06521c9f18e adds early heartbeat message, maybe that's the case.
*edit:* did it also turn on by itself with the older fw?

Transitions are also reworked to avoid pointlessly waiting for very small or zero steps.

Comment (davebuk) [reply code/espurna/tuya_util.h:61]: With all versions of espurna, a cold boot would bring the light ON. The only way to sync the ON/OFF state before was with the physical GPIO button and I think using the webui. MQTT wouldn't sync the switch/relay status.

Possibly completely not relevant..., a normal device would read the button high/low state at boot. As a button is not defined but I guess discovered, could the device be trying to read an unknown button state from the electronic noise at boot, I guess high at boot unless held low, and triggering the ON state?

Comment (mcspr) [reply code/espurna/tuya_util.h:61]: As I understood it - "The Wi-Fi module resets the network configuration by detecting the GPIO input pin." - MCU won't touch it by itself, but only sends the factory-selected configuration for the WiFi part
https://developer.tuya.com/en/docs/iot/device-development/embedded-software-development/mcu-development-access/wifi-mcu-sdk-solution/tuya-cloud-universal-serial-port-access-protocol?id=K9hhi0xxtn9cb#title-7-Querying%20working%20mode

Both GPIOs are already set via `btnGPIO0` and `ledGPIO0` in the logs above, but idk if that is really affects this in any way. You could `del` them both though just to try it out and set them later manually (since tuya.save won't have those, as discovery is never called with manual config)

**Comment by davebuk** [comment]
2487095 with either transitions ON or OFF brings light ON at 100% after cold boot (RED LED), but webUI and GREEN LED (unlit) indicate the light is OFF. Selecting ON in the webUI turns the light ON to the pervious brightness (40%) and the GREEN LED ON.

- With transitions ON, MQTT dimming stops working correctly. I requested a 5% increase from 40-45%, then 45-50%. The returned openHAB percent went to 50% then to 49%

40-45%
```
[758811] [MQTT] Received TUYA001/channel/0/set => 114.75
[758814] [LIGHT] schedule target=114 step=-2.25 count=8
[758916] [MQTT] Sending TUYA001/channel/0 => 114 (PID 1)
[758917] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
```
45-50%
```
[777383] [MQTT] Received TUYA001/channel/0/set => 126.7499999999999937
[777385] [LIGHT] schedule target=126 step=1.50 count=8
[777488] [MQTT] Sending TUYA001/channel/0 => 126 (PID 1)
[777489] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
```
- With transitions OFF, MQTT dimming works as before but after selecting a new value I get a constant stream of IN/OUT data simlar to:
```
[623584] [TUYA] =>: 55aa0006000802020004000000667b
[623619] [TUYA] <=: 55aa0007000802020004000000667c
[623788] [TUYA] =>: 55aa0006000802020004000000667b
[623823] [TUYA] <=: 55aa0007000802020004000000667c
[623993] [TUYA] =>: 55aa0006000802020004000000667b
[624028] [TUYA] <=: 55aa0007000802020004000000667c
[624198] [TUYA] =>: 55aa0006000802020004000000667b
[624233] [TUYA] <=: 55aa0007000802020004000000667c
[624401] [TUYA] =>: 55aa0006000802020004000000667b
[624436] [TUYA] <=: 55aa0007000802020004000000667c
[624607] [TUYA] =>: 55aa0006000802020004000000667b
[624643] [TUYA] <=: 55aa0007000802020004000000667c
[624812] [TUYA] =>: 55aa0006000802020004000000667b
[624847] [TUYA] <=: 55aa0007000802020004000000667c
```

Could you just program for the TUYA provider, `if` transitions OFF, time/step is 500ms/500ms, `else` use transition settings. Or does the code not work like that?

**Comment by mcspr** [comment]
Transitions OFF bugs were expected, ON is strange... Does it want a rounded value? It thought it already returned values like that, it just takes the integer just like the previous implementation

Can you check the boot log with the current build?

**Comment by davebuk** [comment]
- MQTT, the first one worked, `114.75` but `126.7499999999999937` didn't. Maybe openHAB didn't round the integer correctly?

- https://github.com/xoseperez/espurna/commit/24870953b6dfead1e9fd26265213c06521c9f18e with transitions ON cold boot:
```
[030411] [WEBSOCKET] Requested action: dbgcmd
[030412] [DEBUG] Buffer size: 4049 / 4096 bytes
[000119] [TELNET] Listening on port 23
[000122] [WEBSERVER] Webserver running on port 80
[000127] [LIGHT] LIGHT_PROVIDER = 3
[000127] [LIGHT] Number of channels: 0
[000149] [RELAY] Number of relays: 1, boot mask: 0b1
[000150] [RELAY] #0 set to OFF
[000176] [BUTTON] Number of buttons: 1
[000182] [LED] Number of leds: 1
[000319] [TUYA] =>: 55aa00000000ff
[000336] [RELAY] Number of relays: 1, boot mask: 0b1
[000337] [LIGHT] Number of channels: 1
[000344] [LIGHT] schedule target=0 step=0.00 count=1
[000348] [WIFI] Scanning
[000348] [RELAY] #0 set to OFF
[000547] [TUYA] =>: 55aa0006000501010001000d
[000960] [TUYA] <=: 55aa0007000501010001010f
[000972] [TUYA] <=: 55aa0007000802020004000000ff15
[001350] [RELAY] Relay mask: 0b0
[003501] [TUYA] =>: 55aa00000000ff
[003531] [MDNS] OK
[004532] [MQTT] MQTT brokers found: 0
[005005] [MQTT] Connecting to broker at 192.168.1.222:1883
[005005] [MQTT] Client ID: TUYA-001
[005006] [MQTT] QoS: 0
[005006] [MQTT] Retain flag: 0
[005006] [MQTT] Keepalive time: 300s
[005006] [MQTT] Will topic: TUYA001/status
[005015] [MQTT] Connected!
[005016] [MQTT] Unsubscribing to # (PID 1)
[005017] [MQTT] Subscribing to TUYA001/brightness/set (PID 2)
[005018] [MQTT] Subscribing to TUYA001/channel/+/set (PID 3)
[005018] [MQTT] Subscribing to TUYA001/relay/+/set (PID 4)
[005018] [MQTT] Subscribing to TUYA001/pulse/+/set (PID 5)
[005020] [MQTT] Subscribing to TUYA001/led/+/set (PID 6)
[005020] [MQTT] Subscribing to TUYA001/action/set (PID 7)
[005248] [MQTT] Subscribe ACK for PID 2
[005248] [MQTT] Subscribe ACK for PID 3
[005248] [MQTT] Subscribe ACK for PID 4
[005248] [MQTT] Subscribe ACK for PID 5
[005249] [MQTT] Subscribe ACK for PID 6
[005249] [MQTT] Subscribe ACK for PID 7
[006509] [TUYA] =>: 55aa00000000ff
[006531] [TUYA] <=: 55aa000000010101
[006531] [TUYA] Already configured
[007557] [MQTT] Sending TUYA001/app => ESPURNA (PID 1)
[007558] [MQTT] Sending TUYA001/version => 1.15.0-dev (24870953) (PID 1)
[007559] [MQTT] Sending TUYA001/board => TUYA_GENERIC_DIMMER (PID 1)
[007560] [MQTT] Sending TUYA001/host => ESPURNA-A6CCBD (PID 1)
[033523] [TUYA] =>: 55aa00000000ff
[033547] [TUYA] <=: 55aa000000010101
```

**Comment by mcspr** [comment]
> Could you just program for the TUYA provider, if transitions OFF, time/step is 500ms/500ms, else use transition settings. Or does the code not work like that?

The idea right now is to replace initial setup with heartbeat ping-pong, and only then configure + do stuff with channels and switches, maybe every 100ms. It will respond eventually on cold boot, either before switches so we could send overrides, or after and it will still be current ON / OFF but slightly faster and independent of transition time

Thanks for the logs, will need to adjust that + transitions. (and I should've mentioned broken OFF mode, sry, I changed the method behaviour but forgot the special case for no transitions)

> MQTT, the first one worked, 114.75 but 126.7499999999999937 didn't. Maybe openHAB didn't round the integer correctly?

It probably expects at least 127 rounded... perhaps related to the type, [I remember adding this to the wiki](https://github.com/xoseperez/espurna/wiki/MQTT#openhab), since brightness would be stable unlike the channel

**Comment by davebuk** [comment]
`del btnGPIO0` and `ledGPIO0` didn't effect the light ON at cold boot.

File: code/espurna/tuya.cpp [hunk 4]
```diff
@@ -197,57 +349,63 @@ namespace Tuya {
...
+                if (!configDone) {
+                    DEBUG_MSG_P(PSTR("[TUYA] Attempting to configure the board ...\n"));
+#if LIGHT_PROVIDER == LIGHT_PROVIDER_CUSTOM
+                    setupChannels();
+#endif
+                    setupSwitches();
+                }
+
+                if (!configDone) {
+                    DEBUG_MSG_P(PSTR("[TUYA] Starting discovery\n"));
```
Comment (mcspr) [inline code/espurna/tuya.cpp:377]: As mentioned, now this waits until serial receives at least one heartbeat message (sending every ~200 ... ~400 ... ~600 ms and etc. to which the MCU must respond)

File: code/espurna/light.cpp [hunk 5]
```diff
@@ -607,27 +647,106 @@ unsigned int _toPWM(unsigned char id) {
...
+        _time(time),
+        _step(step)
+    {
+        bool action { false };
+        for (auto& channel : channels) {
+            float diff = static_cast<float>(channel.target) - channel.current;
+            if (!time || (std::abs(diff) <= std::numeric_limits<float>::epsilon())) {
+                channel.current = channel.target;
+                continue;
+            }
```
Comment (mcspr) [inline code/espurna/light.cpp]: Also reworked 'empty' condition. Either time is 0 (transitions disabled) or transition is too small - it simply does nothing, but still triggers the channel update

File: code/espurna/light.cpp [hunk 6]
```diff
@@ -607,27 +647,106 @@ unsigned int _toPWM(unsigned char id) {
...
+
+            action = true;
+
+            float channel_step = (diff > 0.0) ? 1.0f : -1.0f;
+            float every = static_cast<double>(time) / std::abs(diff);
+            if (every < _step) {
+                channel_step *= (static_cast<float>(_step) / every);
+                every = static_cast<float>(_step);
+            }
+            size_t count = time / every;
```
Comment (mcspr) [inline code/espurna/light.cpp]: This also changes the LIGHT_PROVIDER_DIMMER transitions, but I have not tested that yet

**Comment by davebuk** [comment]
So far, all is looking good. I'll put up some post boot logs soon but the light quickly goes from ON to OFF after a cold boot with transitions OFF or ON.

Dimming seems to be working ok via MQTT.

Other than the boot logs, is there any particular testing or logs you would like?

**Comment by davebuk** [comment]
- Cold boot - transitions OFF:
```
[000125] [LIGHT] Provider: CUSTOM
[000149] [RELAY] Number of relays: 1, boot mask: 0b1
[000149] [RELAY] #0 set to OFF
[000175] [BUTTON] Number of buttons: 1
[000182] [LED] Number of leds: 1
[000183] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000183] [MQTT] Client DISABLED, DISCONNECTED
[000314] [TUYA] =>: 55aa00000000ff
[000332] [RELAY] Number of relays: 1, boot mask: 0b1
[000335] [WIFI] Scanning
[000336] [RELAY] #0 set to OFF
[000523] [TUYA] =>: 55aa00000000ff
[000925] [TUYA] =>: 55aa00000000ff
[000957] [TUYA] <=: 55aa0007000501010001010f
[000969] [TUYA] <=: 55aa0007000802020004000000ff15
[001337] [RELAY] Relay mask: 0b0
[001535] [TUYA] =>: 55aa00000000ff
[001556] [TUYA] <=: 55aa000000010000
[001556] [TUYA] Attempting to configure the board ...
[001571] [LIGHT] Number of channels: 1
[001591] [TUYA] =>: 55aa0006000501010001000d
[001623] [TUYA] <=: 55aa0007000501010001000e
[001634] [TUYA] <=: 55aa0007000501010001000e
[001646] [TUYA] <=: 55aa0007000802020004000000ff15
[001667] [TUYA] <=: 55aa0007000501010001000e
[001678] [TUYA] <=: 55aa00070008020200040000001026
[002343] [TUYA] =>: 55aa00000000ff
[002365] [TUYA] <=: 55aa000000010101
[003538] [MDNS] OK
[004539] [MQTT] MQTT brokers found: 0
[005003] [MQTT] Client ID: TUYA-001
[005003] [MQTT] QoS: 0
[005003] [MQTT] Retain flag: 0
[005003] [MQTT] Keepalive time: 300s
[005003] [MQTT] Will topic: TUYA001/status
[005012] [MQTT] Connected!
[005013] [MQTT] Unsubscribing to # (PID 1)
[005014] [MQTT] Subscribing to TUYA001/brightness/set (PID 2)
[005015] [MQTT] Subscribing to TUYA001/channel/+/set (PID 3)
[005015] [MQTT] Subscribing to TUYA001/relay/+/set (PID 4)
[020350] [TUYA] =>: 55aa00000000ff
[020375] [TUYA] <=: 55aa000000010101
```
- Cold boot, transitions ON (2000/100ms):
```
[000127] [LIGHT] Provider: CUSTOM
[000150] [RELAY] Number of relays: 1, boot mask: 0b1
[000151] [RELAY] #0 set to OFF
[000177] [BUTTON] Number of buttons: 1
[000183] [LED] Number of leds: 1
[000316] [TUYA] =>: 55aa00000000ff
[000333] [RELAY] Number of relays: 1, boot mask: 0b1
[000336] [WIFI] Scanning
[000337] [RELAY] #0 set to OFF
[000524] [TUYA] =>: 55aa00000000ff
[000925] [TUYA] =>: 55aa00000000ff
[000947] [TUYA] <=: 55aa0007000501010001010f
[000968] [TUYA] <=: 55aa0007000802020004000000ff15
[001338] [RELAY] Relay mask: 0b0
[001534] [TUYA] =>: 55aa00000000ff
[001556] [TUYA] <=: 55aa000000010000
[001556] [TUYA] Attempting to configure the board ...
[001570] [LIGHT] Number of channels: 1
[001591] [TUYA] =>: 55aa0006000501010001000d
[001623] [TUYA] <=: 55aa0007000501010001000e
[001634] [TUYA] <=: 55aa0007000501010001000e
[001645] [TUYA] <=: 55aa0007000802020004000000ff15
[001667] [TUYA] <=: 55aa0007000501010001000e
[001678] [TUYA] <=: 55aa00070008020200040000001026
[002341] [TUYA] =>: 55aa00000000ff
[002363] [TUYA] <=: 55aa000000010101
[005007] [MQTT] Client ID: TUYA-001
[005007] [MQTT] QoS: 0
[005007] [MQTT] Retain flag: 0
[005007] [MQTT] Keepalive time: 300s
[005008] [MQTT] Will topic: TUYA001/status
[005018] [MQTT] Connected!
[005018] [MQTT] Unsubscribing to # (PID 1)
[005020] [MQTT] Subscribing to TUYA001/brightness/set (PID 2)
[005020] [MQTT] Subscribing to TUYA001/channel/+/set (PID 3)
[005021] [MQTT] Subscribing to TUYA001/relay/+/set (PID 4)
[005021] [MQTT] Subscribing to TUYA001/pulse/+/set (PID 5)
[005023] [MQTT] Subscribing to TUYA001/led/+/set (PID 6)
[005023] [MQTT] Subscribing to TUYA001/action/set (PID 7)
[020354] [TUYA] =>: 55aa00000000ff
[020378] [TUYA] <=: 55aa000000010101
```

- Light ON-OFF from webUI with transitions ON:
```
[152705] [WEBSOCKET] Requested action: relay
[152706] [RELAY] #0 scheduled ON in 0 ms
[152715] [RELAY] #0 set to ON
[152716] [LIGHT] Transition from=0.00 to=255 step=12.75 times=20
[152716] [LIGHT] Scheduled transition every 100 (total 2000)
[152718] [MQTT] Sending TUYA001/relay/0 => 1 (PID 1)
[152818] [MQTT] Sending TUYA001/channel/0 => 255 (PID 1)
[152819] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[152934] [TUYA] =>: 55aa0006000802020004000000192e
[152970] [TUYA] <=: 55aa0007000802020004000000192f
[152983] [TUYA] <=: 55aa0007000501010001010f
[152998] [TUYA] <=: 55aa00070008020200040000003a50
[153044] [TUYA] =>: 55aa0006000802020004000000263b
[153079] [TUYA] <=: 55aa0007000802020004000000263c
[153145] [TUYA] =>: 55aa00060008020200040000003348
[153180] [TUYA] <=: 55aa00070008020200040000003349
[153194] [TUYA] <=: 55aa0007000501010001010f
[153208] [TUYA] <=: 55aa00070008020200040000004359
[153253] [TUYA] =>: 55aa00060008020200040000003f54
[153288] [TUYA] <=: 55aa00070008020200040000003f55
[153302] [TUYA] <=: 55aa0007000501010001010f
[153318] [TUYA] <=: 55aa00070008020200040000004e64
[153354] [TUYA] =>: 55aa00060008020200040000004c61
[153389] [TUYA] <=: 55aa00070008020200040000004c62
[153403] [TUYA] <=: 55aa0007000501010001010f
[153418] [TUYA] <=: 55aa00070008020200040000005c72
[153464] [TUYA] =>: 55aa0006000802020004000000596e
[153499] [TUYA] <=: 55aa0007000802020004000000596f
[153513] [TUYA] <=: 55aa0007000501010001010f
[153528] [TUYA] <=: 55aa0007000802020004000000677d
[153574] [TUYA] =>: 55aa0006000802020004000000667b
[153609] [TUYA] <=: 55aa0007000802020004000000667c
[153625] [TUYA] <=: 55aa0007000501010001010f
[153640] [TUYA] <=: 55aa0007000802020004000000758b
[153675] [TUYA] =>: 55aa00060008020200040000007287
[153710] [TUYA] <=: 55aa00070008020200040000007288
[153723] [RELAY] Relay mask: 0b1
[153726] [TUYA] <=: 55aa0007000501010001010f
[153741] [TUYA] <=: 55aa00070008020200040000008096
[153776] [TUYA] =>: 55aa00060008020200040000007f94
[153811] [TUYA] <=: 55aa00070008020200040000007f95
[153825] [TUYA] <=: 55aa0007000501010001010f
[153838] [TUYA] <=: 55aa00070008020200040000008ea4
[153885] [TUYA] =>: 55aa00060008020200040000008ca1
[153920] [TUYA] <=: 55aa00070008020200040000008ca2
[153934] [TUYA] <=: 55aa0007000501010001010f
[153949] [TUYA] <=: 55aa00070008020200040000009cb2
[153994] [TUYA] =>: 55aa000600080202000400000099ae
[154029] [TUYA] <=: 55aa000700080202000400000099af
[154044] [TUYA] <=: 55aa0007000501010001010f
[154058] [TUYA] <=: 55aa0007000802020004000000a8be
[154094] [TUYA] =>: 55aa0006000802020004000000a5ba
[154129] [TUYA] <=: 55aa0007000802020004000000a5bb
[154143] [TUYA] <=: 55aa0007000501010001010f
[154157] [TUYA] <=: 55aa0007000802020004000000b3c9
[154204] [TUYA] =>: 55aa0006000802020004000000b2c7
[154239] [TUYA] <=: 55aa0007000802020004000000b2c8
[154253] [TUYA] <=: 55aa0007000501010001010f
[154267] [TUYA] <=: 55aa0007000802020004000000c1d7
[154313] [TUYA] =>: 55aa0006000802020004000000bfd4
[154349] [TUYA] <=: 55aa0007000802020004000000bfd5
[154363] [TUYA] <=: 55aa0007000501010001010f
[154377] [TUYA] <=: 55aa0007000802020004000000cfe5
[154423] [TUYA] =>: 55aa0006000802020004000000cce1
[154458] [TUYA] <=: 55aa0007000802020004000000cce2
[154472] [TUYA] <=: 55aa0007000501010001010f
[154486] [TUYA] <=: 55aa0007000802020004000000daf0
[154532] [TUYA] =>: 55aa0006000802020004000000d8ed
[154568] [TUYA] <=: 55aa0007000802020004000000d8ee
[154582] [TUYA] <=: 55aa0007000501010001010f
[154596] [TUYA] <=: 55aa0007000802020004000000e8fe
[154642] [TUYA] =>: 55aa0006000802020004000000e5fa
[154678] [TUYA] <=: 55aa0007000802020004000000e5fb
[154692] [TUYA] <=: 55aa0007000501010001010f
[154706] [TUYA] <=: 55aa0007000802020004000000f309
[154753] [TUYA] =>: 55aa0006000802020004000000f207
[154788] [TUYA] <=: 55aa0007000802020004000000f208
[154801] [TUYA] <=: 55aa0007000501010001010f
[154816] [TUYA] <=: 55aa0007000802020004000000ff15
[154862] [TUYA] =>: 55aa0006000802020004000000ff14
[154897] [TUYA] <=: 55aa0007000802020004000000ff15
[155419] [TUYA] =>: 55aa00000000ff
[155443] [TUYA] <=: 55aa000000010101
[156649] [WEBSOCKET] Requested action: relay
[156650] [RELAY] #0 scheduled OFF in 0 ms
[156653] [RELAY] #0 set to OFF
[156654] [LIGHT] Transition from=255.00 to=0 step=-12.75 times=20
[156655] [LIGHT] Scheduled transition every 100 (total 2000)
[156657] [MQTT] Sending TUYA001/relay/0 => 0 (PID 1)
[156757] [MQTT] Sending TUYA001/channel/0 => 0 (PID 1)
[156758] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[156767] [TUYA] =>: 55aa0006000802020004000000f207
[156800] [TUYA] <=: 55aa0007000802020004000000f208
[156866] [TUYA] =>: 55aa0006000802020004000000e5fa
[156901] [TUYA] <=: 55aa0007000802020004000000e5fb
[156915] [TUYA] <=: 55aa0007000501010001010f
[156929] [TUYA] <=: 55aa0007000802020004000000f309
[156975] [TUYA] =>: 55aa0006000802020004000000d8ed
[157011] [TUYA] <=: 55aa0007000802020004000000d8ee
[157027] [TUYA] <=: 55aa0007000501010001010f
[157040] [TUYA] <=: 55aa0007000802020004000000e8fe
[157078] [TUYA] =>: 55aa0006000802020004000000cce1
[157115] [TUYA] <=: 55aa0007000802020004000000cce2
[157129] [TUYA] <=: 55aa0007000501010001010f
[157143] [TUYA] <=: 55aa0007000802020004000000daf0
[157178] [TUYA] =>: 55aa0006000802020004000000bfd4
[157214] [TUYA] <=: 55aa0007000802020004000000bfd5
[157228] [TUYA] <=: 55aa0007000501010001010f
[157242] [TUYA] <=: 55aa0007000802020004000000cfe5
[157288] [TUYA] =>: 55aa0006000802020004000000b2c7
[157323] [TUYA] <=: 55aa0007000802020004000000b2c8
[157337] [TUYA] <=: 55aa0007000501010001010f
[157350] [TUYA] <=: 55aa0007000802020004000000c1d7
[157395] [TUYA] =>: 55aa0006000802020004000000a5ba
[157431] [TUYA] <=: 55aa0007000802020004000000a5bb
[157444] [TUYA] <=: 55aa0007000501010001010f
[157459] [TUYA] <=: 55aa0007000802020004000000b3c9
[157504] [TUYA] =>: 55aa000600080202000400000099ae
[157542] [TUYA] <=: 55aa000700080202000400000099af
[157554] [TUYA] <=: 55aa0007000501010001010f
[157566] [TUYA] <=: 55aa0007000802020004000000a8be
[157612] [TUYA] =>: 55aa00060008020200040000008ca1
[157653] [TUYA] <=: 55aa00070008020200040000008ca2
[157659] [RELAY] Relay mask: 0b0
[157665] [TUYA] <=: 55aa0007000501010001010f
[157677] [TUYA] <=: 55aa00070008020200040000009cb2
[157720] [TUYA] =>: 55aa00060008020200040000007f94
[157754] [TUYA] <=: 55aa00070008020200040000007f95
[157769] [TUYA] <=: 55aa0007000501010001010f
[157781] [TUYA] <=: 55aa00070008020200040000008ea4
[157826] [TUYA] =>: 55aa00060008020200040000007287
[157863] [TUYA] <=: 55aa00070008020200040000007288
[157877] [TUYA] <=: 55aa0007000501010001010f
[157891] [TUYA] <=: 55aa00070008020200040000008096
[157927] [TUYA] =>: 55aa0006000802020004000000667b
[157963] [TUYA] <=: 55aa0007000802020004000000667c
[157975] [TUYA] <=: 55aa0007000501010001010f
[157997] [TUYA] <=: 55aa0007000802020004000000758b
[158030] [TUYA] =>: 55aa0006000802020004000000596e
[158063] [TUYA] <=: 55aa0007000802020004000000596f
[158085] [TUYA] <=: 55aa0007000501010001010f
[158097] [TUYA] <=: 55aa0007000802020004000000677d
```

- Light ON from MQTT then change from 100% to 40%
```
[335659] [MQTT] Received TUYA001/relay/0/set => 1
[335661] [RELAY] #0 scheduled ON in 0 ms
[335665] [RELAY] #0 set to ON
[335666] [LIGHT] Transition from=0.00 to=255 step=12.75 times=20
[335666] [LIGHT] Scheduled transition every 100 (total 2000)
[335668] [MQTT] Sending TUYA001/relay/0 => 1 (PID 1)
[335768] [MQTT] Sending TUYA001/channel/0 => 255 (PID 1)
[335769] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[335883] [TUYA] =>: 55aa0006000802020004000000192e
[335918] [TUYA] <=: 55aa0007000802020004000000192f
[335932] [TUYA] <=: 55aa0007000501010001010f
[335947] [TUYA] <=: 55aa00070008020200040000003a50
[335993] [TUYA] =>: 55aa0006000802020004000000263b
[336028] [TUYA] <=: 55aa0007000802020004000000263c
[336094] [TUYA] =>: 55aa00060008020200040000003348
[336129] [TUYA] <=: 55aa00070008020200040000003349
[336143] [TUYA] <=: 55aa0007000501010001010f
[336157] [TUYA] <=: 55aa00070008020200040000004359
[336204] [TUYA] =>: 55aa00060008020200040000003f54
[336239] [TUYA] <=: 55aa00070008020200040000003f55
[336253] [TUYA] <=: 55aa0007000501010001010f
[336267] [TUYA] <=: 55aa00070008020200040000004e64
[336315] [TUYA] =>: 55aa00060008020200040000004c61
[336350] [TUYA] <=: 55aa00070008020200040000004c62
[336364] [TUYA] <=: 55aa0007000501010001010f
[336378] [TUYA] <=: 55aa00070008020200040000005c72
[336424] [TUYA] =>: 55aa0006000802020004000000596e
[336459] [TUYA] <=: 55aa0007000802020004000000596f
[336473] [TUYA] <=: 55aa0007000501010001010f
[336488] [TUYA] <=: 55aa0007000802020004000000677d
[336534] [TUYA] =>: 55aa0006000802020004000000667b
[336569] [TUYA] <=: 55aa0007000802020004000000667c
[336583] [TUYA] <=: 55aa0007000501010001010f
[336597] [TUYA] <=: 55aa0007000802020004000000758b
[336643] [TUYA] =>: 55aa00060008020200040000007287
[336671] [RELAY] Relay mask: 0b1
[336680] [TUYA] <=: 55aa00070008020200040000007288
[336694] [TUYA] <=: 55aa0007000501010001010f
[336709] [TUYA] <=: 55aa00070008020200040000008096
[336744] [TUYA] =>: 55aa00060008020200040000007f94
[336779] [TUYA] <=: 55aa00070008020200040000007f95
[336793] [TUYA] <=: 55aa0007000501010001010f
[336807] [TUYA] <=: 55aa00070008020200040000008ea4
[336853] [TUYA] =>: 55aa00060008020200040000008ca1
[336888] [TUYA] <=: 55aa00070008020200040000008ca2
[336902] [TUYA] <=: 55aa0007000501010001010f
[336917] [TUYA] <=: 55aa00070008020200040000009cb2
[336963] [TUYA] =>: 55aa000600080202000400000099ae
[336998] [TUYA] <=: 55aa000700080202000400000099af
[337012] [TUYA] <=: 55aa0007000501010001010f
[337027] [TUYA] <=: 55aa0007000802020004000000a8be
[337073] [TUYA] =>: 55aa0006000802020004000000a5ba
[337108] [TUYA] <=: 55aa0007000802020004000000a5bb
[337122] [TUYA] <=: 55aa0007000501010001010f
[337137] [TUYA] <=: 55aa0007000802020004000000b3c9
[337173] [TUYA] =>: 55aa0006000802020004000000b2c7
[337208] [TUYA] <=: 55aa0007000802020004000000b2c8
[337222] [TUYA] <=: 55aa0007000501010001010f
[337236] [TUYA] <=: 55aa0007000802020004000000c1d7
[337282] [TUYA] =>: 55aa0006000802020004000000bfd4
[337317] [TUYA] <=: 55aa0007000802020004000000bfd5
[337331] [TUYA] <=: 55aa0007000501010001010f
[337344] [TUYA] <=: 55aa0007000802020004000000cfe5
[337389] [TUYA] =>: 55aa0006000802020004000000cce1
[337424] [TUYA] <=: 55aa0007000802020004000000cce2
[337438] [TUYA] <=: 55aa0007000501010001010f
[337452] [TUYA] <=: 55aa0007000802020004000000daf0
[337497] [TUYA] =>: 55aa0006000802020004000000d8ed
[337533] [TUYA] <=: 55aa0007000802020004000000d8ee
[337547] [TUYA] <=: 55aa0007000501010001010f
[337562] [TUYA] <=: 55aa0007000802020004000000e8fe
[337598] [TUYA] =>: 55aa0006000802020004000000e5fa
[337633] [TUYA] <=: 55aa0007000802020004000000e5fb
[337647] [TUYA] <=: 55aa0007000501010001010f
[337661] [TUYA] <=: 55aa0007000802020004000000f309
[337700] [TUYA] =>: 55aa0006000802020004000000f207
[337736] [TUYA] <=: 55aa0007000802020004000000f208
[337750] [TUYA] <=: 55aa0007000501010001010f
[337764] [TUYA] <=: 55aa0007000802020004000000ff15
[337810] [TUYA] =>: 55aa0006000802020004000000ff14
[337845] [TUYA] <=: 55aa0007000802020004000000ff15
[342994] [MQTT] Received TUYA001/channel/0/set => 102
[342997] [LIGHT] Transition from=255.00 to=102 step=-7.65 times=20
[342997] [LIGHT] Scheduled transition every 100 (total 2000)
[343100] [MQTT] Sending TUYA001/channel/0 => 102 (PID 1)
[343100] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[343112] [TUYA] =>: 55aa0006000802020004000000f70c
[343145] [TUYA] <=: 55aa0007000802020004000000f70d
[343209] [TUYA] =>: 55aa0006000802020004000000ef04
[343247] [TUYA] <=: 55aa0007000802020004000000ef05
[343261] [TUYA] <=: 55aa0007000501010001010f
[343276] [TUYA] <=: 55aa0007000802020004000000fe14
[343312] [TUYA] =>: 55aa0006000802020004000000e8fd
[343347] [TUYA] <=: 55aa0007000802020004000000e8fe
[343360] [TUYA] <=: 55aa0007000501010001010f
[343375] [TUYA] <=: 55aa0007000802020004000000f60c
[343421] [TUYA] =>: 55aa0006000802020004000000e0f5
[343456] [TUYA] <=: 55aa0007000802020004000000e0f6
[343469] [TUYA] <=: 55aa0007000501010001010f
[343485] [TUYA] <=: 55aa0007000802020004000000f006
[343531] [TUYA] =>: 55aa0006000802020004000000d8ed
[343566] [TUYA] <=: 55aa0007000802020004000000d8ee
[343580] [TUYA] <=: 55aa0007000501010001010f
[343595] [TUYA] <=: 55aa0007000802020004000000e8fe
[343641] [TUYA] =>: 55aa0006000802020004000000d1e6
[343676] [TUYA] <=: 55aa0007000802020004000000d1e7
[343691] [TUYA] <=: 55aa0007000501010001010f
[343705] [TUYA] <=: 55aa0007000802020004000000e0f6
[343751] [TUYA] =>: 55aa0006000802020004000000c9de
[343786] [TUYA] <=: 55aa0007000802020004000000c9df
[343800] [TUYA] <=: 55aa0007000501010001010f
[343815] [TUYA] <=: 55aa0007000802020004000000d7ed
[343861] [TUYA] =>: 55aa0006000802020004000000c1d6
[343897] [TUYA] <=: 55aa0007000802020004000000c1d7
[343910] [TUYA] <=: 55aa0007000501010001010f
[343925] [TUYA] <=: 55aa0007000802020004000000cfe5
[343970] [TUYA] =>: 55aa0006000802020004000000bacf
[344006] [TUYA] <=: 55aa0007000802020004000000bad0
[344020] [TUYA] <=: 55aa0007000501010001010f
[344034] [TUYA] <=: 55aa0007000802020004000000c9df
[344080] [TUYA] =>: 55aa0006000802020004000000b2c7
[344115] [TUYA] <=: 55aa0007000802020004000000b2c8
[344129] [TUYA] <=: 55aa0007000501010001010f
[344144] [TUYA] <=: 55aa0007000802020004000000c1d7
[344189] [TUYA] =>: 55aa0006000802020004000000aabf
[344226] [TUYA] <=: 55aa0007000802020004000000aac0
[344239] [TUYA] <=: 55aa0007000501010001010f
[344254] [TUYA] <=: 55aa0007000802020004000000b8ce
[344290] [TUYA] =>: 55aa0006000802020004000000a3b8
[344325] [TUYA] <=: 55aa0007000802020004000000a3b9
[344339] [TUYA] <=: 55aa0007000501010001010f
[344353] [TUYA] <=: 55aa0007000802020004000000b3c9
[344399] [TUYA] =>: 55aa00060008020200040000009bb0
[344435] [TUYA] <=: 55aa00070008020200040000009bb1
[344448] [TUYA] <=: 55aa0007000501010001010f
[344463] [TUYA] <=: 55aa0007000802020004000000aac0
[344509] [TUYA] =>: 55aa000600080202000400000093a8
[344545] [TUYA] <=: 55aa000700080202000400000093a9
[344545] [TUYA] =>: 55aa00000000ff
[344559] [TUYA] <=: 55aa0007000501010001010f
[344573] [TUYA] <=: 55aa0007000802020004000000a2b8
[344588] [TUYA] <=: 55aa000000010101
[344614] [TUYA] =>: 55aa00060008020200040000008ca1
[344650] [TUYA] <=: 55aa00070008020200040000008ca2
[344663] [TUYA] <=: 55aa0007000501010001010f
[344676] [TUYA] <=: 55aa00070008020200040000009cb2
[344720] [TUYA] =>: 55aa00060008020200040000008499
[344755] [TUYA] <=: 55aa0007000802020004000000849a
[344769] [TUYA] <=: 55aa0007000501010001010f
[344783] [TUYA] <=: 55aa000700080202000400000094aa
[344830] [TUYA] =>: 55aa00060008020200040000007c91
[344865] [TUYA] <=: 55aa00070008020200040000007c92
[344878] [TUYA] <=: 55aa0007000501010001010f
[344893] [TUYA] <=: 55aa00070008020200040000008ca2
[344930] [TUYA] =>: 55aa0006000802020004000000758a
[344965] [TUYA] <=: 55aa0007000802020004000000758b
[344979] [TUYA] <=: 55aa0007000501010001010f
[344993] [TUYA] <=: 55aa00070008020200040000008399
[345041] [TUYA] =>: 55aa00060008020200040000006d82
[345076] [TUYA] <=: 55aa00070008020200040000006d83
[345091] [TUYA] <=: 55aa0007000501010001010f
[345106] [TUYA] <=: 55aa00070008020200040000007b91
[345142] [TUYA] =>: 55aa0006000802020004000000667b
[345177] [TUYA] <=: 55aa0007000802020004000000667c
[345191] [TUYA] <=: 55aa0007000501010001010f
[345205] [TUYA] <=: 55aa0007000802020004000000758b
[353553] [TUYA] =>: 55aa00000000ff
[353578] [TUYA] <=: 55aa000000010101
```

- MQTT 5% increase from 40% to 45% then 45% to 50%:
```
[413831] [MQTT] Received TUYA001/channel/0/set => 114.75
[413834] [LIGHT] Transition from=102.00 to=114 step=1.00 times=12
[413834] [LIGHT] Scheduled transition every 100 (total 2000)
[413937] [MQTT] Sending TUYA001/channel/0 => 114 (PID 1)
[413937] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[413946] [TUYA] =>: 55aa0006000802020004000000677c
[413979] [TUYA] <=: 55aa0007000802020004000000677d
[414046] [TUYA] =>: 55aa0006000802020004000000687d
[414082] [TUYA] <=: 55aa0007000802020004000000687e
[414095] [TUYA] <=: 55aa0007000501010001010f
[414109] [TUYA] <=: 55aa0007000802020004000000788e
[414155] [TUYA] =>: 55aa0006000802020004000000697e
[414191] [TUYA] <=: 55aa0007000802020004000000697f
[414257] [TUYA] =>: 55aa00060008020200040000006a7f
[414292] [TUYA] <=: 55aa00070008020200040000006a80
[414360] [TUYA] =>: 55aa00060008020200040000006b80
[414395] [TUYA] <=: 55aa00070008020200040000006b81
[414408] [TUYA] <=: 55aa0007000501010001010f
[414423] [TUYA] <=: 55aa00070008020200040000007b91
[414470] [TUYA] =>: 55aa00060008020200040000006c81
[414505] [TUYA] <=: 55aa00070008020200040000006c82
[414571] [TUYA] =>: 55aa00060008020200040000006d82
[414607] [TUYA] <=: 55aa00070008020200040000006d83
[414673] [TUYA] =>: 55aa00060008020200040000006e83
[414708] [TUYA] <=: 55aa00070008020200040000006e84
[414723] [TUYA] <=: 55aa0007000501010001010f
[414737] [TUYA] <=: 55aa00070008020200040000007e94
[414763] [MQTT] Received TUYA001/channel/0/set => 127.5
[414765] [LIGHT] Transition from=110.00 to=127 step=1.00 times=17
[414766] [LIGHT] Scheduled transition every 100 (total 2000)
[414868] [MQTT] Sending TUYA001/channel/0 => 127 (PID 1)
[414869] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[414879] [TUYA] =>: 55aa00060008020200040000006f84
[414912] [TUYA] <=: 55aa00070008020200040000006f85
[414978] [TUYA] =>: 55aa00060008020200040000007085
[415014] [TUYA] <=: 55aa00070008020200040000007086
[415027] [TUYA] <=: 55aa0007000501010001010f
[415042] [TUYA] <=: 55aa00070008020200040000008096
[415089] [TUYA] =>: 55aa00060008020200040000007186
[415124] [TUYA] <=: 55aa00070008020200040000007187
[415191] [TUYA] =>: 55aa00060008020200040000007287
[415226] [TUYA] <=: 55aa00070008020200040000007288
[415292] [TUYA] =>: 55aa00060008020200040000007388
[415327] [TUYA] <=: 55aa00070008020200040000007389
[415341] [TUYA] <=: 55aa0007000501010001010f
[415356] [TUYA] <=: 55aa00070008020200040000008399
[415401] [TUYA] =>: 55aa00060008020200040000007489
[415436] [TUYA] <=: 55aa0007000802020004000000748a
[415503] [TUYA] =>: 55aa0006000802020004000000758a
[415538] [TUYA] <=: 55aa0007000802020004000000758b
[415604] [TUYA] =>: 55aa0006000802020004000000768b
[415640] [TUYA] <=: 55aa0007000802020004000000768c
[415654] [TUYA] <=: 55aa0007000501010001010f
[415669] [TUYA] <=: 55aa0007000802020004000000869c
[415715] [TUYA] =>: 55aa0006000802020004000000778c
[415750] [TUYA] <=: 55aa0007000802020004000000778d
[415816] [TUYA] =>: 55aa0006000802020004000000788d
[415851] [TUYA] <=: 55aa0007000802020004000000788e
[415917] [TUYA] =>: 55aa0006000802020004000000798e
[415952] [TUYA] <=: 55aa0007000802020004000000798f
[415966] [TUYA] <=: 55aa0007000501010001010f
[415981] [TUYA] <=: 55aa0007000802020004000000899f
[416027] [TUYA] =>: 55aa00060008020200040000007a8f
[416062] [TUYA] <=: 55aa00070008020200040000007a90
[416128] [TUYA] =>: 55aa00060008020200040000007b90
[416163] [TUYA] <=: 55aa00070008020200040000007b91
[416230] [TUYA] =>: 55aa00060008020200040000007c91
[416265] [TUYA] <=: 55aa00070008020200040000007c92
[416279] [TUYA] <=: 55aa0007000501010001010f
[416293] [TUYA] <=: 55aa00070008020200040000008ca2
[416339] [TUYA] =>: 55aa00060008020200040000007d92
[416374] [TUYA] <=: 55aa00070008020200040000007d93
[416440] [TUYA] =>: 55aa00060008020200040000007e93
[416475] [TUYA] <=: 55aa00070008020200040000007e94
[416489] [TUYA] <=: 55aa0007000501010001010f
[416504] [TUYA] <=: 55aa00070008020200040000008ea4
[416549] [TUYA] =>: 55aa00060008020200040000007f94
[416584] [TUYA] <=: 55aa00070008020200040000007f95
[416598] [TUYA] =>: 55aa00000000ff
[416621] [TUYA] <=: 55aa000000010101
```

- MQTT OFF from 50%:
```
[604886] [MQTT] Received TUYA001/relay/0/set => 0
[604889] [RELAY] #0 scheduled OFF in 0 ms
[604892] [RELAY] #0 set to OFF
[604894] [LIGHT] Transition from=127.00 to=0 step=-6.35 times=20
[604894] [LIGHT] Scheduled transition every 100 (total 2000)
[604896] [MQTT] Sending TUYA001/relay/0 => 0 (PID 1)
[604997] [MQTT] Sending TUYA001/channel/0 => 0 (PID 1)
[604997] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[605008] [TUYA] =>: 55aa0006000802020004000000788d
[605034] [MQTT] Sending TUYA001/app => ESPURNA (PID 1)
[605035] [MQTT] Sending TUYA001/version => 1.15.0-dev (91942d67) (PID 1)
[605036] [MQTT] Sending TUYA001/board => TUYA_GENERIC_DIMMER (PID 1)
[605040] [MQTT] Sending TUYA001/host => ESPURNA-A6CCBD (PID 1)
[605043] [MQTT] Sending TUYA001/desc => Dining Light (PID 1)
[605047] [MQTT] Sending TUYA001/mac => BC:DD:C2:A6:CC:BD (PID 1)
[605052] [MQTT] Sending TUYA001/rssi => -65 (PID 1)
[605057] [MQTT] Sending TUYA001/uptime => 605 (PID 1)
[605058] [MQTT] Sending TUYA001/datetime => 2021-01-11 19:44:48 (PID 1)
[605061] [MQTT] Sending TUYA001/freeheap => 19536 (PID 1)
[605062] [MQTT] Sending TUYA001/relay/0 => 0 (PID 1)
[605062] [MQTT] Sending TUYA001/channel/0 => 0 (PID 1)
[605063] [MQTT] Sending TUYA001/brightness => 255 (PID 1)
[605064] [MQTT] Sending TUYA001/vcc => 3493 (PID 1)
[605068] [MQTT] Sending TUYA001/status => 1 (PID 1)
[605071] [MQTT] Sending TUYA001/loadavg => 1 (PID 1)
[605074] [TUYA] <=: 55aa0007000802020004000000788e
[605077] [TUYA] <=: 55aa0007000501010001010f
[605081] [TUYA] <=: 55aa0007000802020004000000869c
[605109] [TUYA] =>: 55aa00060008020200040000007287
[605144] [TUYA] <=: 55aa00070008020200040000007288
[605158] [TUYA] <=: 55aa0007000501010001010f
[605172] [TUYA] <=: 55aa00070008020200040000008096
[605218] [TUYA] =>: 55aa00060008020200040000006b80
[605253] [TUYA] <=: 55aa00070008020200040000006b81
[605267] [TUYA] <=: 55aa0007000501010001010f
[605281] [TUYA] <=: 55aa00070008020200040000007b91
[605328] [TUYA] =>: 55aa0006000802020004000000657a
[605364] [TUYA] <=: 55aa0007000802020004000000657b
[605377] [TUYA] <=: 55aa0007000501010001010f
[605391] [TUYA] <=: 55aa0007000802020004000000758b
[605438] [TUYA] =>: 55aa00060008020200040000005f74
[605473] [TUYA] <=: 55aa00070008020200040000005f75
[605487] [TUYA] <=: 55aa0007000501010001010f
[605501] [TUYA] <=: 55aa00070008020200040000006d83
[605548] [TUYA] =>: 55aa0006000802020004000000586d
[605583] [TUYA] <=: 55aa0007000802020004000000586e
[605597] [TUYA] <=: 55aa0007000501010001010f
[605612] [TUYA] <=: 55aa0007000802020004000000677d
[605658] [TUYA] =>: 55aa00060008020200040000005267
[605693] [TUYA] <=: 55aa00070008020200040000005268
[605707] [TUYA] <=: 55aa0007000501010001010f
[605722] [TUYA] <=: 55aa00070008020200040000006278
[605723] [TUYA] =>: 55aa00000000ff
[605748] [TUYA] <=: 55aa000000010101
[605762] [TUYA] =>: 55aa00060008020200040000004c61
[605797] [TUYA] <=: 55aa00070008020200040000004c62
[605811] [TUYA] <=: 55aa0007000501010001010f
[605827] [TUYA] <=: 55aa00070008020200040000005c72
[605863] [TUYA] =>: 55aa0006000802020004000000455a
[605898] [TUYA] <=: 55aa0007000802020004000000455b
[605900] [RELAY] Relay mask: 0b0
[605912] [TUYA] <=: 55aa0007000501010001010f
[605927] [TUYA] <=: 55aa0007000802020004000000546a
[605973] [TUYA] =>: 55aa00060008020200040000003f54
[606009] [TUYA] <=: 55aa00070008020200040000003f55
[606023] [TUYA] <=: 55aa0007000501010001010f
[606038] [TUYA] <=: 55aa00070008020200040000004e64
[606083] [TUYA] =>: 55aa0006000802020004000000394e
[606118] [TUYA] <=: 55aa0007000802020004000000394f
[606130] [TUYA] <=: 55aa0007000501010001010f
[606154] [TUYA] <=: 55aa0007000802020004000000485e
[606189] [TUYA] =>: 55aa00060008020200040000003247
[606224] [TUYA] <=: 55aa00070008020200040000003248
[606238] [TUYA] <=: 55aa0007000501010001010f
[606253] [TUYA] <=: 55aa00070008020200040000004056
[606300] [TUYA] =>: 55aa00060008020200040000002c41
[606336] [TUYA] <=: 55aa00070008020200040000002c42
[606350] [TUYA] <=: 55aa0007000501010001010f
[606365] [TUYA] <=: 55aa00070008020200040000003a50
[606409] [TUYA] =>: 55aa0006000802020004000000263b
[606446] [TUYA] <=: 55aa0007000802020004000000263c
[606512] [TUYA] =>: 55aa00060008020200040000001f34
[606547] [TUYA] <=: 55aa00070008020200040000001f35
[606614] [TUYA] =>: 55aa0006000802020004000000192e
[606650] [TUYA] <=: 55aa0007000802020004000000192f
[606717] [TUYA] =>: 55aa00060008020200040000001328
[606752] [TUYA] <=: 55aa00070008020200040000001329
[607026] [TUYA] =>: 55aa0006000501010001000d
[607061] [TUYA] <=: 55aa0007000501010001000e
[607075] [TUYA] <=: 55aa0007000501010001000e
[607089] [TUYA] <=: 55aa00070008020200040000003a50
[607104] [TUYA] <=: 55aa0007000501010001000e
[607118] [TUYA] <=: 55aa00070008020200040000001026
```

**Comment by davebuk** [comment]
Video of the light with transition set to 2000/100ms going from OFF to 100% to OFF. The brightness is relatively smooth but the video doesn't show it that well.  

https://user-images.githubusercontent.com/3661426/104233338-9f7c4780-5449-11eb-8a81-79c2d70e94f7.mp4

**Comment by mcspr** [comment]
Thanks!  If you happen to have any LIGHT_PROVIDER_DIMMER devices, that would be interesting to know whether it looks any different.

And I assume normal boot is still ok? Only odd thing I noticed and will push another update for is that it initializes the same relays twice:
```
[000150] [RELAY] Number of relays: 1, boot mask: 0b1
[000151] [RELAY] #0 set to OFF
...
[000333] [RELAY] Number of relays: 1, boot mask: 0b1
[000337] [RELAY] #0 set to OFF
...
```
(e.g. when relay boot mode set to toggle, this may switch things unexpectedly)

**Comment by davebuk** [comment]
2b2fb4f Now I get:
```
[000149] [RELAY] Number of relays: 1, boot mask: 0b1
[000150] [RELAY] #0 set to OFF
[001150] [RELAY] Relay mask: 0b0
```
Yes, the light defaults to OFF after a cold boot or `REBOOT` from the webUI.

**Comment by davebuk** [comment]
I have tried a `MAGICHOME_ZJ_WFMN_C_11` single channel LED dimmer. 
`debug.buffer` gives:
```
[017773] [DEBUG] Buffer size: 4087 / 4096 bytes
[000109] [TELNET] Listening on port 23
[000112] [WEBSERVER] Webserver running on port 80
[000116] [LIGHT] Provider: DIMMER
[000118] [LIGHT] Number of channels: 1
[000141] [RELAY] Number of relays: 2, boot mask: 0b0
[000142] [RELAY] #0 set to OFF
[000144] [RELAY] #1 set to OFF
[000165] [BUTTON] Number of buttons: 1
[000170] [LED] Number of leds: 1
[000171] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000172] [MQTT] Client DISABLED, DISCONNECTED
[000193] [NTP] Startup delay: 3s, Update delay: 2437s
[000200] [NTP] Server: pool.ntp.org, TZ: CET0CEST,M3.5.0,M10.5.0/3
[000296] [WIFI] Scanning
[001145] [RELAY] Relay mask: 0b0
[003568] [WIFI] ----------------------------------------------
[003576] [MDNS] OK
[004578] [MQTT] MQTT brokers found: 0
[005004] [MQTT] Client ID: LED_001
[005004] [MQTT] QoS: 1
[005004] [MQTT] Retain flag: 1
[005005] [MQTT] Keepalive time: 300s
[005008] [MQTT] Will topic: LED001/status
[005070] [MQTT] Connected!
[005071] [MQTT] Unsubscribing to # (PID 1)
[005073] [MQTT] Subscribing to LED001/brightness/set (PID 2)
[005073] [MQTT] Subscribing to LED001/transition/set (PID 3)
[005076] [MQTT] Subscribing to LED001/channel/+/set (PID 4)
[005082] [MQTT] Subscribing to LED001/relay/+/set (PID 5)
[005087] [MQTT] Subscribing to LED001/pulse/+/set (PID 6)
[005093] [MQTT] Subscribing to LED001/led/+/set (PID 7)
[005097] [MQTT] Subscribing to LED001/action/set (PID 8)
[005204] [NTP] Server     : pool.ntp.org
[005205] [NTP] Sync Time  : 2021-01-12 19:53:30 (UTC)
[005205] [NTP] UTC Time   : 2021-01-12 19:53:30
[005206] [NTP] Local Time : 2021-01-12 19:53:30 (CET0CEST,M3.5.0,M10.5.0/3)
[005215] [MQTT] Sending LED001/app => ESPURNA (PID 9)
[005218] [MQTT] Sending LED001/version => 1.15.0-dev (2b2fb4f9) (PID 10)
[005225] [MQTT] Sending LED001/board => MAGICHOME_LED_WHITE (PID 11)
[005230] [MQTT] Sending LED001/host => ESP-LED001 (PID 12)
[005236] [MQTT] Sending LED001/desc => Dining Room Cupboards (PID 13)
[005251] [MQTT] Sending LED001/mac => DC:4F:22:A2:ED:07 (PID 16)
[005257] [MQTT] Sending LED001/rssi => -56 (PID 17)
[005261] [MQTT] Sending LED001/uptime => 5 (PID 18)
[005266] [MQTT] Sending LED001/datetime => 2021-01-12 19:53:30 (PID 19)
[005272] [MQTT] Sending LED001/freeheap => 21960 (PID 20)
[005277] [MQTT] Sending LED001/relay/0 => 0 (PID 21)
[005281] [MQTT] Sending LED001/relay/1 => 0 (PID 22)
```
As the log shows, two relays are set. `#0` controls the output and dimming/MQTT works. The dummy switch `#1` doesn't do anything. If I select NO for the option under 'LIGHTS' to add a virtual relay and reboot, only one switch is shown `Switch #0 (dummy)` and the relay doesn't control anything.
```
[026615] [DEBUG] Buffer size: 4084 / 4096 bytes
[000110] [TELNET] Listening on port 23
[000112] [WEBSERVER] Webserver running on port 80
[000116] [LIGHT] Provider: DIMMER
[000119] [LIGHT] Number of channels: 1
[000138] [RELAY] Number of relays: 1, boot mask: 0b0
[000139] [RELAY] #0 set to OFF
[000160] [BUTTON] Number of buttons: 1
[000165] [LED] Number of leds: 1
[000166] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000166] [MQTT] Client DISABLED, DISCONNECTED
[000188] [NTP] Startup delay: 5s, Update delay: 2374s
[000195] [NTP] Server: pool.ntp.org, TZ: CET0CEST,M3.5.0,M10.5.0/3
[000282] [WIFI] Scanning
[001140] [RELAY] Relay mask: 0b0
[004620] [WIFI] ----------------------------------------------
[004628] [MDNS] OK
[005630] [MQTT] MQTT brokers found: 0
[005631] [MQTT] Client ID: LED_001
[005631] [MQTT] QoS: 1
[005632] [MQTT] Retain flag: 1
[005635] [MQTT] Keepalive time: 300s
[005638] [MQTT] Will topic: LED001/status
[005675] [MQTT] Connected!
[005676] [MQTT] Unsubscribing to # (PID 1)
[005678] [MQTT] Subscribing to LED001/brightness/set (PID 2)
[005678] [MQTT] Subscribing to LED001/transition/set (PID 3)
[005681] [MQTT] Subscribing to LED001/channel/+/set (PID 4)
[005686] [MQTT] Subscribing to LED001/light/set (PID 5)
[005691] [MQTT] Subscribing to LED001/relay/+/set (PID 6)
[005696] [MQTT] Subscribing to LED001/pulse/+/set (PID 7)
[005702] [MQTT] Subscribing to LED001/led/+/set (PID 8)
[005706] [MQTT] Subscribing to LED001/action/set (PID 9)
[005871] [WEBSERVER] GET /index.html
[005913] [MQTT] Subscribe ACK for PID 2
[005914] [MQTT] Subscribe ACK for PID 3
[005914] [MQTT] Subscribe ACK for PID 4
[005914] [MQTT] Subscribe ACK for PID 5
[005916] [MQTT] Subscribe ACK for PID 6
[005920] [MQTT] Subscribe ACK for PID 7
[005923] [MQTT] Subscribe ACK for PID 8
[005927] [MQTT] Subscribe ACK for PID 9
[006020] [WEBSERVER] GET /auth
[009632] [NTP] Server     : pool.ntp.org
[009632] [NTP] Sync Time  : 2021-01-12 20:05:31 (UTC)
[009633] [NTP] UTC Time   : 2021-01-12 20:05:31
[009633] [NTP] Local Time : 2021-01-12 20:05:31 (CET0CEST,M3.5.0,M10.5.0/3)
[009643] [MQTT] Sending LED001/app => ESPURNA (PID 10)
[009645] [MQTT] Sending LED001/version => 1.15.0-dev (2b2fb4f9) (PID 11)
[009653] [MQTT] Publish ACK for PID 10
[009657] [MQTT] Sending LED001/board => MAGICHOME_LED_WHITE (PID 12)
[009662] [MQTT] Publish ACK for PID 11
```

**Comment by mcspr** [comment]
Thanks again!

> The dummy switch #1 doesn't do anything. If I select NO for the option under 'LIGHTS' to add a virtual relay and reboot, only one switch is shown Switch #0 (dummy) and the relay doesn't control anything.

I should also note that DUMMY_RELAY_COUNT flag is no longer required to have the switch present and instead controlled via the setting or the LIGHT_RELAY_ENABLED flag with 0 or 1. I modified every hardware.h entry, but custom config needs to be updated 

This PR also looses an ability to control individual channels via relays, but idk if that was even used (or was apparent enough in the config to be used at all by anybody). I have kept an example of how to do that though, so it should be easy to add back

**Comment by davebuk** [comment]
Is there any reason the term "RELAY" has to be used? The relay is represented and also referred to by a switch, which can be controlled by a button or switch.

Could "RELAY" be replaced with "OUTPUT" or something else? I appreciate it could be quite a bit of change in the base code!

**Comment by mcspr** [comment]
Main reasoning here is that it depends on the whole 'RELAY_SUPPORT=1', and everything that goes with it - pulse, boot modes, sync etc. When disabling the switch, lights still have basic API control (for example, MQTT messages 0 / 1 via `{root}/light` and `{root}/light/set`), but none of the 'relay' specific features are available.

RELAY_SUPPORT itself though... idk, mainly historical reasons and I don't really see the point renaming it atm.

**Comment by mcspr** [comment]
And from the WebUI side as well - "Switch #..." naming was added as early as https://github.com/xoseperez/espurna/commit/d426969fb2488dc2eb916a55215bdf79a7d43f90#diff-afb0a4f2bad82b1e7b81fd330ad5f47dff2289155b708964cdff821bf4d35ac2R350
PR also adds a cfg key `relayName#`, which will be used instead of the placeholder name for the `#`'th relay

**Comment by davebuk** [comment]
That's fine. It's something that confused me early on when taking about buttons and switches as input controls attached to GPIOs, and switches and relays as the output controls, which may _actually_ control a relay or maybe a PWM GPIO! 😁

**Comment by mcspr** [comment]
Note that authors so far are not native English speakers :)
Yeah, and some places should probably have a bit different wording; e.g. "Switch management" in readme mentioning buttons, switches and relay switches right after the other or the wiki page saying switches and referring to relays later on. Or the original PR that added tuyaSwitch\#, which is really both a button and a relay controlled by some boolean value send or received (if we ever see more tuya devices supported)

**Comment by davebuk** [comment]
Like you said, it's fine as it is. Maybe some changes in the wiki would help noobs like me. I may look at offering some amendments in the future. 😊

**Comment by davebuk** [comment]
FYI, after more testing a transition setting of 2000/100ms hasn't always turned the light OFF after a cold boot. 2000/200ms seems to be OK. Its not as smooth but seems more reliable.

**Comment by mcspr** [comment]
Any logs?
One thing comes to mind - `tuyaFilter` is no longer a DPid, but a global boolean value. In case you still have it set to `2`, it may accidentally read the remote ON state. Either setting to `1` or removing it (default is that already) should ignore the messages again.
Otherwise, I'd look at the Heartbeat timeout value. Maybe it needs slightly longer step (+50 or +100ms), see `HeartbeatIncrement` in the tuya.cpp

**Comment by davebuk** [comment]
I have `tuyaFilter 1` but also have `tuyafilter 2` which I may have added with the lower case 'f' by accident? `del tuyafilter` comes up with an error. Would these two keys conflict with each other?

**Comment by mcspr** [comment]
Settings are case-sensitive, so the first key is selected.
ref. the second issue, are there really two keys when looking at `eeprom.dump` output?

**Comment by davebuk** [comment]
For some reason, all webUI debug commands give an error saying "Command not found". I've tried a warm and cold reboot and it still doesn't work. I'll try re loading the .bin

**Comment by davebuk** [comment]
OFF TOPIC - the version and commit version shown top left of the webUI are now merged e.g 
was: `1.15.0-dev (2b2fb4f9)` newer build `1.15.0-dev8e659c94` just looks less pretty :-)

I had to load a previous build, 1.15.0-dev (2b2fb4f9) `tuyafilter` is there. I was able to delete it using `del tuyafilter`
```
0x0B70:  00 06 30 62 31 00 03 72 65 6C 61 79 42 6F 6F 74   0b1  relayBoot
0x0B80:  4D 61 73 6B 00 0D 31 00 01 64 62 67 4C 6F 67 42 Mask  1  dbgLogB
0x0B90:  75 66 00 09 31 00 01 74 75 79 61 43 68 61 6E 53 uf  1  tuyaChanS
0x0BA0:  74 61 74 65 00 0D 30 00 01 6D 69 72 65 64 73 00 tate  0  mireds 
0x0BB0:  06 32 35 35 00 03 62 72 69 67 68 74 6E 65 73 73  255  brightness
0x0BC0:  00 0A 32 00 01 74 75 79 61 43 68 61 6E 6E 65 6C   2  tuyaChannel
0x0BD0:  30 00 0C 30 00 01 74 75 79 61 53 77 69 74 63 68 0  0  tuyaSwitch
0x0BE0:  30 00 0B 54 55 59 41 5F 47 45 4E 45 52 49 43 5F 0  TUYA_GENERIC_
0x0BF0:  44 49 4D 4D 45 52 00 13 62 6F 61 72 64 4E 61 6D DIMMER  boardNam
0x0C00:  65 00 09 31 36 34 00 03 63 68 31 00 03 32 00 01 e  164  ch1  2  
0x0C10:  74 75 79 61 66 69 6C 74 65 72 00 0A 32 00 01 6C tuyafilter  2  l
0x0C20:  65 64 4D 6F 64 65 30 00 08 31 39 32 2E 31 36 38 edMode0  192.168
0x0C30:  2E 31 2E 31 00 0B 64 6E 73 30 00 04 31 32 38 00 .1.1  dns0  128 
0x0C40:  03 73 79 73 53 63 54 72 61 63 65 4D 61 78 00 0D  sysScTraceMax  
0x0C50:  31 00 01 6D 71 74 74 45 6E 61 62 6C 65 64 00 0B 1  mqttEnabled  
0x0C60:  6F 70 65 6E 68 61 62 69 61 6E 00 0A 6D 71 74 74 openhabian  mqtt
0x0C70:  55 73 65 72 00 08 30 00 01 6D 71 74 74 51 6F 53 User  0  mqttQoS
0x0C80:  00 07 30 00 01 75 73 65 52 47 42 00 06 30 00 01   0  useRGB  0  
0x0C90:  75 73 65 43 6F 6C 6F 72 00 08 30 00 01 72 65 6C useColor  0  rel
0x0CA0:  61 79 4C 61 73 74 53 63 68 30 00 0D 31 39 32 2E ayLastSch0 
0x0CB0:  31 36 38 2E 31 2E 32 32 32 00 0D 6D 71 74 74 53   mqttS
0x0CC0:  65 72 76 65 72 00 0A 44 69 6E 69 6E 67 20 4C 69 erver  Dining Li
0x0CD0:  67 68 74 00 0C 64 65 73 63 00 04 31 39 32 2E 31 ght  desc  
0x0CE0:  36 38 2E 31 2E 31 00 0B 67 77 30 00 03 31 39 32  gw0  
0x0CF0:  2E 31 36 38 2E 31 2E 34 33 00 0C 69 70 30 00 03   ip0  
0x0D00:  31 00 01 74 75 79 61 46 69 6C 74 65 72 00 0A 54 1  tuyaFilter
```

**Comment by mcspr** [comment]
What is the message log on boot though? No need to change transition time atm.

**Comment by davebuk** [comment]
Built using standard TUYA environment settings with latest commit.
```
[005842] [WEBSOCKET] #1 connected, ip: 192.168. url: /ws
[011338] [TUYA] =>: 55aa00000000ff
[011362] [TUYA] <=: 55aa000000010101
[020258] [WEBSOCKET] Requested action: dbgcmd
[020260] [DEBUG] Buffer size: 4081 / 4096 bytes
[000118] [TELNET] Listening on port 23
[000120] [WEBSERVER] Webserver running on port 80
[000125] [LIGHT] Provider: CUSTOM
[000148] [RELAY] Number of relays: 1, boot mask: 0b1
[000149] [RELAY] #0 set to OFF
[000175] [BUTTON] Number of buttons: 1
[000181] [LED] Number of leds: 1
[000182] [MQTT] AsyncMqttClient, SSL DISABLED, Autoconnect ENABLED, Buffer size 1024 bytes
[000182] [MQTT] Client DISABLED, DISCONNECTED
[000202] [NTP] Startup delay: 3s, Update delay: 2760s
[000215] [THINGSPEAK] Async ENABLED, SSL DISABLED
[000309] [TUYA] =>: 55aa00000000ff
[000329] [WIFI] Scanning
[000515] [TUYA] =>: 55aa00000000ff
[000918] [TUYA] =>: 55aa00000000ff
[000950] [TUYA] <=: 55aa0007000501010001010f
[000961] [TUYA] <=: 55aa0007000802020004000000ff15
[001150] [RELAY] Relay mask: 0b0
[001526] [TUYA] =>: 55aa00000000ff
[001548] [TUYA] <=: 55aa000000010000
[001548] [TUYA] Attempting to configure the board ...
[001562] [LIGHT] Number of channels: 1
[001583] [TUYA] =>: 55aa0006000501010001000d
[001615] [TUYA] <=: 55aa0007000501010001000e
[001626] [TUYA] <=: 55aa0007000501010001000e
[001637] [TUYA] <=: 55aa0007000802020004000000ff15
[001659] [TUYA] <=: 55aa0007000501010001000e
[001670] [TUYA] <=: 55aa00070008020200040000001026
[002334] [TUYA] =>: 55aa00000000ff
[002355] [TUYA] <=: 55aa000000010101
[003515] [NTP] Updating `ntpServer` setting from DHCP: (IP unset)
[003524] [WIFI] Captive portal disabled
[003524] [WIFI] ------------------------------------- MODE STA
[003524] [WIFI] SSID 
[003525] [WIFI] IP   
[003525] [WIFI] MAC   
[003525] [WIFI] GW    192.168.1.1
[003526] [WIFI] DNS   192.168.1.1
[003526] [WIFI] MASK  255.255.255.0
[003526] [WIFI] HOST  http://ESPURNA-A6CCBD.local
[003526] [WIFI] BSSID 
[003527] [WIFI] CH    1
[003527] [WIFI] RSSI  -64
[003527] [WIFI] ----------------------------------------------
[003529] [MDNS] OK
[004530] [MQTT] MQTT brokers found: 0
[005001] [MQTT] Connecting to broker at 
[005001] [MQTT] Client ID: TUYA-001
[005002] [MQTT] QoS: 0
[005002] [MQTT] Retain flag: 0
[005002] [MQTT] Keepalive time: 300s
[005002] [MQTT] Will topic: TUYA001/status
[005002] [MQTT] Connecting as user
[005011] [MQTT] Connected!
[005012] [MQTT] Unsubscribing to # (PID 1)
[005013] [MQTT] Subscribing to TUYA001/brightness/set (PID 2)
[005014] [MQTT] Subscribing to TUYA001/transition/set (PID 3)
[005014] [MQTT] Subscribing to TUYA001/channel/+/set (PID 4)
[005014] [MQTT] Subscribing to TUYA001/relay/+/set (PID 5)
[005015] [MQTT] Subscribing to TUYA001/pulse/+/set (PID 6)
[005016] [MQTT] Subscribing to TUYA001/led/+/set (PID 7)
[005017] [MQTT] Subscribing to TUYA001/action/set (PID 8)
[005241] [MQTT] Subscribe ACK for PID 2
[005241] [MQTT] Subscribe ACK for PID 3
[005241] [MQTT] Subscribe ACK for PID 4
[005241] [MQTT] Subscribe ACK for PID 5
[005241] [MQTT] Subscribe ACK for PID 6
[005242] [MQTT] Subscribe ACK for PID 7
[005242] [MQTT] Subscribe ACK for PID 8
[020340] [TUYA] =>: 55aa00000000ff
[020364] [TUYA] <=: 55aa000000010101
```
Seems to be working again after deleting that key!

**Comment by davebuk** [comment]
In case its important, the version I was running where I lost access to terminal commands was built using:
```
#elif defined(DB_TUYA_DIMMER)

    // Info
    #define MANUFACTURER        "TUYA"
    #define DEVICE              "GENERIC_DIMMER"

    //My config
    #define ALEXA_SUPPORT           0
    #define DOMOTICZ_SUPPORT        0
    #define HOMEASSISTANT_SUPPORT   0
    #define THINGSPEAK_SUPPORT      0
    #define NTP_TIMEZONE			TZ_Europe_London
	
    #define TUYA_SUPPORT        1
    #define LIGHT_PROVIDER      LIGHT_PROVIDER_CUSTOM
    #define BUTTON_MQTT_SEND_ALL_EVENTS     1
```
Also, the NTP server setting has been deleted in the eeprom by defining the `NTP_TIMEZONE` only. I think I'll just leave the option out in future and just fill in the timezone details in the webUI once the device is running.

**Comment by mcspr** [comment]
> [003515] [NTP] Updating `ntpServer` setting from DHCP: (IP unset)

This looks like a separate issue with the DHCP packets coming from the router running the DHCP server or the way those are parsed, it should contain some valid data and not `IP unset`

**Comment by davebuk** [comment]
1.15.0-dev.git660493a1 

I'm still having issues with DEBUG commands in the webUI when building with the settings below. Commenting out the NTP stuff doesn't make any difference. `CRASH`, `INFO` etc brings up an error and `debug.buffer` gives: `-ERROR: Command line buffer overflow`. The standard environment works fine and other devices using the same 'My config' settings works fine, so it must be a TUYA issue. I'm trying to see the `keys` to check the NTP data.
```
#elif defined(DB_TUYA_DIMMER)

    // Info
    #define MANUFACTURER        "TUYA"
    #define DEVICE              "GENERIC_DIMMER"

    //My config
    #define ALEXA_SUPPORT           0
    #define DOMOTICZ_SUPPORT        0
    #define HOMEASSISTANT_SUPPORT   0
    #define THINGSPEAK_SUPPORT      0
    #define NTP_TIMEZONE			TZ_Europe_London
	
    #define TUYA_SUPPORT        1
    #define LIGHT_PROVIDER      LIGHT_PROVIDER_CUSTOM
```

**Comment by mcspr** [comment]
`#define DEBUG_SERIAL_SUPPORT 0`?

**Comment by davebuk** [comment]
FIXED!
Why would that work where as the standard environment was fine!

**Comment by davebuk** [comment]
Except I've lost LED from the webUI and the green LED has stopped coming ON. 😂

**Comment by davebuk** [comment]
Just looked and 1.15.0-devacf29958, standard tuya build has also lost LED. Only `ledMode0` is in the keys.

**Comment by mcspr** [comment]
Discovery never gets to run in the latest build when config is present. Unless manually set, both btnGPIO0 (0) and ledGPIO0 (14) won't show up
You can just add them build flags though?

**Comment by davebuk** [comment]
I was just trying that, yep adding those keys has returned the LED to webUI and GREEN LED is working again.

**Comment by davebuk** [comment]
The button thing is another issue I was going to mention. I have only recently noticed, the physical button turns the device ON/OFF but only to 100% and doesn't show the correct state in the webUI. It brings ON the RED LED only. I guess its bypassing the ESP and controlling the MCU directly? I was trying to get the BUTTON_ACTION to dim UP/DOWN with double and long press, but that doesn't work from build definitions.

**Comment by davebuk** [comment]
After doing the factory reset on this device I had to re run: `set tuyaChanState 1, set tuyaSwitch0 0 and set tuyaChannel0 2`. LED had gone again even though `tuya.show` listed it and the button GPIO. `tuya.save` and a reboot has restored the LED in webUI without having to `set` the keys. Both LED and BUTTON GPIOs are also listed in the `keys`. The physical button turns the light ON/OFF but doesn't show it's state in the webUI or MQTT.

**Comment by davebuk** [comment]
Debug data when pressing the button from an OFF state, the light then now turns ON at a dim level (webUI shows 102) and then pressing again which returns to OFF. The RED LED goes ON/OFF but the GREEN doesn't.
```
[912598] [TUYA] <=: 55aa0007000501010001010f
[912624] [TUYA] <=: 55aa00070008020200040000001026
[912636] [TUYA] <=: 55aa0007000501010001010f
[912648] [TUYA] <=: 55aa00070008020200040000003a50
[915380] [TUYA] =>: 55aa00000000ff
[915406] [TUYA] <=: 55aa000000010101
[916667] [TUYA] <=: 55aa0007000501010001000e
[916681] [TUYA] <=: 55aa00070008020200040000003a50
[916694] [TUYA] <=: 55aa0007000501010001000e
[916707] [TUYA] <=: 55aa00070008020200040000001026
```

**Comment by timmeh87** [comment]
I am using exact same generic tasmota inline dimmer device that davebuk has (at least the one pictured in #1729)

I flashed the latest commit of espurna onto it (this is literally my first attempt ever at flashing this particular device).

Without "debug_serial_support" set to zero, I got one slider and one switch, and it did not work. After disabling debug serial support, I now get two switches and two sliders, one slider is called "channel #0" and one is called "brightness", and between these two switches and two sliders, they all seem to affect the state of the dimmer, but in a really random way. I cant even really describe it. Sometimes the either switch might work to either turn the output fully on, or fully off, but sometimes they also dont do anything. Depending on the switches state, either slider might be controlling the actual brightness while the other one has no effect, or vice versa. after playing with one control or the other, the effect other controls have seems to change like a game of whack-a-mole.

I figure theres gotta be a bug here somewhere, let me know if I can help somehow

**Comment by davebuk** [comment]
@mcspr Is the expert but I can say what I've done. I believe the TUYA code makes an output/relay using some code from a discovery routine. I have then had to use the following commands in the webUI DEBUG console one at a time. `set tuyaChanState 1`, `set tuyaSwitch0 0` and `set tuyaChannel0 2` followed by `tuya.save`. Reboot and you should have just one switch and two sliders. Set brightness to 255 and leave it there. Brightness is controlled by the channel 0 slider. Give it a go and see what you get. There is a separate issue with the physical button but Max is working his magic. 😁

**Comment by timmeh87** [comment]
Oh true. I did manage to put them into the console per your previous message but I never saved or rebooted. duh! Ill try this tonight. Thank you!

**Comment by timmeh87** [comment]
I can report back that your instructions worked (After doing a "factory reset"), I see the one button and 2 sliders as you said. I also have noticed that changing the slider from a high value to any value to 0 - 16 results in no change until a value greater than 16 is selected. So for example if the power is 100 and you click on "9" on the slider, the power will still be 100. I think I saw a change recently that ignores values 0-16, but I think it would be good to set the value to 16 still, so its still close to what the slider says instead of up to 84 points off. 

Ok well let it be known that I have this hardware and am running the latest code on it and anyone can message me if they need me to try something out.

**Comment by davebuk** [comment]
I don't think I tried values that low since the original testing when the device was first added to the code base.

It could be worth you making sure that after a cold boot, mains power OFF/ON, the output ends up at OFF. You may see the output flick ON then OFF but it should end up after boot to OFF.

You could also try turning transitions ON under the lights menu. I'm currently running 1600ms time with 100ms steps. With transitions working try a soft and cold reboot and check the output ends up at OFF again.

**Comment by mcspr** [comment]
>  I also have noticed that changing the slider from a high value to any value to 0 - 16 results in no change until a value greater than 16 is selected. So for example if the power is 100 and you click on "9" on the slider, the power will still be 100.

fwiw transitions actually help with the case since they do channel changes step-by-step instead of an immediate jump to the value.
https://github.com/xoseperez/espurna/blob/1b4e515575e89c00705f3c26bafa86247bf8f056/code/espurna/tuya.cpp#L150
but this part may be changed to replace the value to 16 instead of just returning

I'd open a new issue though, github pagination is the worst and this discussion relates to the already-merged code, not the code in the PR
